# -*- coding: utf-8



MONTHS = (
        ('01', 'Enero'),
        ('02', 'Febrero'),
        ('03', 'Marzo'),
        ('04', 'Abril'),
        ('05', 'Mayo'),
        ('06', 'Junio'),
        ('07', 'Julio'),
        ('08', 'Agosto'),
        ('09', 'Septiembre'),
        ('10', 'Octubre'),
        ('11', 'Noviembre'),
        ('12', 'Diciembre'),)

DATEPICKER = {
        'type': 'text',
        'class': 'form-control',
        'id': 'datetimepicker4',
 
    }

DATEPICKER2 = {
        'type': 'text',
        'class': 'form-control',
        'id': 'datetimepicker4',
        'readonly':'readonly'
    }

Birthday = {
        'type': 'text',
        'class': 'form-control',
        'id': 'birthday'
    }

HireDate = {
        'type': 'text',
        'class': 'form-control',
        'id': 'hiredate'
    }

EndDate = {
        'type': 'text',
        'class': 'form-control',
        'id': 'enddate'
    }


BloodChoices = (
	('', 'Selecciona un tipo de Sangre'),
	('O-', 'Tipo O-'),
	('O+', 'Tipo O+'),
	('A-', 'Tipo A-'),
	('A+', 'Tipo A+'),
	('B-', 'Tipo B-'),
	('B+', 'Tipo B+'),
	('AB-', 'Tipo AB-'),
	('AB+', 'Tipo AB+'),
	)

GenderChoices = (
	('', 'Selecciona un Genero'),
	('M', 'Masculino'),
	('F', 'Femenino'),
	)

AsesorChoices = (
	('', 'Selecciona un Tipo'),
	('Tipo A', 'Tipo A'),
	('Tipo B', 'Tipo B'),
	('Tipo C', 'Tipo C'),
	('Tipo D', 'Tipo D'),
	('Tipo E', 'Tipo E'),
	)



RelationshipChoices = (
	('', 'Selecciona una Opción'),
	('Conyugue', 'Es su Conyugue'),
	('Padre/Madre', 'Es su Padre o Madre'),
	('Hijo(a)', 'Es su Hijo(a)'),
	('Herman(a)', 'Es su Hermano(a)'),
	('Ninguno', 'No tiene parentesco'),
	)


SOURCE_CHOICES = (

	('', 'Selecciona la Fuente de Contacto'),
	('Pospecto', 'Prospecto'),
	('Llamada', 'Llamada'),
	('Web', 'Web'),

	)

TYPE_CHOICES = (
	('', 'Selecciona el Tipo de Cliente'),
	('Tipo A', 'Tipo A'),
	('Tipo B', 'Tipo B'),
	('Tipo C', 'Tipo C'),
	('Tipo G', 'Tipo G'),
	('Tipo T', 'Tipo T'),

	)


COUNTRY_CHOICES = (
	('Mexico', 'México'),

	)

job_tittle = (
	('', '---Selecciona una opción---'),
	('Director', 'Director'),
	('Gerente General', 'Gerente General'),
	('Ventas', 'Ventas'),
	('Ventas', 'Ventas'),
	('Ventas', 'Ventas'),
	('Ventas', 'Ventas'),
	('Ventas', 'Ventas'),
	('Ventas', 'Ventas'),
	('Ventas', 'Ventas'),
	)



STATE_CHOICES = (
	('', 'Selecciona el Estado'),
	('Aguascalientes', 'Aguascalientes'),
	('Baja California', 'Baja California'),
	('Baja California Sur', 'Baja California Sur'),	
	('Campeche', 'Campeche'),
	('Coahuila', 'Coahuila'),
	('Colima', 'Colima'),
	('Chiapas', 'Chiapas'),
	('Chihuahua', 'Chihuahua'),
	('Distrito', 'Distrito'),
	('Durango', 'Durango'),
	('Guanajuato', 'Guanajuato'),
	('Guerrero', 'Guerrero'),
	('Hidalgo', 'Hidalgo'),
	('Jalisco', 'Jalisco'),
	('México', 'México'),
	('Michoacán de Ocampo', 'Michoacán de Ocampo'),
	('Morelos ', 'Morelos '),
	('Nayarit', 'Nayarit'),
	('Nuevo León', 'Nuevo León'),
	('Oaxaca', 'Oaxaca'),
	('Puebla', 'Puebla'),
	('Querétaro', 'Querétaro'),
	('Quintana Roo', 'Quintana Roo'),
	('San Luis Potosí', 'San Luis Potosí'),
	('Sinaloa', 'Sinaloa'),
	('Sonora', 'Sonora'),
	('Tabasco', 'Tabasco'),
	('Tamaulipas', 'Tamaulipas'),
	('Tlaxcala', 'Tlaxcala'),
	('Veracruz de Ignacio de la Llave', 'Veracruz de Ignacio de la Llave'),
	('Yucatán', 'Yucatán'),
	('Zacatecas','Zacatecas'),
	)
CITY_CHOICES = (
	('', 'Selecciona un Municipio'),
	('Aguascalientes', 'Aguascalientes'),
	('Asientos', 'Asientos'),
	('Calvillo', 'Calvillo'),
	('Cosío', 'Cosío'),
	('Jesús María', 'Jesús María'),
	('Pabellón de Arteaga', 'Pabellón de Arteaga'),
	('Rincón de Romos', 'Rincón de Romos'),
	('San José de Gracia', 'San José de Gracia'),
	('Tepezalá', 'Tepezalá'),
	('El Llano', 'El Llano'),
	('San Francisco de los Romo', 'San Francisco de los Romo'),
	('Ensenada', 'Ensenada'),
	('Mexicali', 'Mexicali'),
	('Tecate', 'Tecate'),
	('Tijuana', 'Tijuana'),
	('Playas de Rosarito', 'Playas de Rosarito'),
	('Comondú', 'Comondú'),
	('Mulegé', 'Mulegé'),
	('La Paz', 'La Paz'),
	('Los Cabos', 'Los Cabos'),
	('Loreto', 'Loreto'),
	('Calkiní', 'Calkiní'),
	('Campeche', 'Campeche'),
	('Carmen', 'Carmen'),
	('Champotón', 'Champotón'),
	('Hecelchakán', 'Hecelchakán'),
	('Hopelchén', 'Hopelchén'),
	('Palizada', 'Palizada'),
	('Tenabo', 'Tenabo'),
	('Escárcega', 'Escárcega'),
	('Calakmul', 'Calakmul'),
	('Candelari', 'Candelari'),
	('Abasolo', 'Abasolo'),
	('Acuña', 'Acuña'),
	('Allende', 'Allende'),
	('Arteaga', 'Arteaga'),
	('Candela', 'Candela'),
	('Castaños', 'Castaños'),
	('Cuatro Ciénegas', 'Cuatro Ciénegas'),
	('Escobedo', 'Escobedo'),
	('Francisco I. Madero', 'Francisco I. Madero'),
	('Frontera', 'Frontera'),
	('General Cepeda', 'General Cepeda'),
	('Guerrero', 'Guerrero'),
	('Hidalgo', 'Hidalgo'),
	('Jiménez', 'Jiménez'),
	('Juárez', 'Juárez'),
	('Lamadrid', 'Lamadrid'),
	('Matamoros', 'Matamoros'),
	('Monclova', 'Monclova'),
	('Morelos', 'Morelos'),
	('Múzquiz', 'Múzquiz'),
	('Nadadores', 'Nadadores'),
	('Nava', 'Nava'),
	('Ocampo', 'Ocampo'),
	('Parras', 'Parras'),
	('Piedras Negras', 'Piedras Negras'),
	('Progreso', 'Progreso'),
	('Ramos Arizpe', 'Ramos Arizpe'),
	('Sabinas', 'Sabinas'),
	('Sacramento', 'Sacramento'),
	('Saltillo', 'Saltillo'),
	('San Buenaventura', 'San Buenaventura'),
	('San Juan de Sabinas', 'San Juan de Sabinas'),
	('San Pedro', 'San Pedro'),
	('Sierra Mojada', 'Sierra Mojada'),
	('Torreón', 'Torreón'),
	('Viesca', 'Viesca'),
	('Villa Unión', 'Villa Unión'),
	('Zaragoza', 'Zaragoza'),
	('Armería', 'Armería'),
	('Colima', 'Colima'),
	('Comala', 'Comala'),
	('Coquimatlán', 'Coquimatlán'),
	('Cuauhtémoc', 'Cuauhtémoc'),
	('Ixtlahuacán', 'Ixtlahuacán'),
	('Manzanillo', 'Manzanillo'),
	('Minatitlán', 'Minatitlán'),
	('Tecomán', 'Tecomán'),
	('Villa de Álvarez', 'Villa de Álvarez'),
	('Acacoyagua', 'Acacoyagua'),
	('Acala', 'Acala'),
	('Acapetahua', 'Acapetahua'),
	('Altamirano', 'Altamirano'),
	('Amatán', 'Amatán'),
	('Amatenango de la Frontera', 'Amatenango de la Frontera'),
	('Amatenango del Valle', 'Amatenango del Valle'),
	('Angel Albino Corzo', 'Angel Albino Corzo'),
	('Arriaga', 'Arriaga'),
	('Bejucal de Ocampo', 'Bejucal de Ocampo'),
	('Bella Vista', 'Bella Vista'),
	('Berriozábal', 'Berriozábal'),
	('Bochil', 'Bochil'),
	('El Bosque', 'El Bosque'),
	('Cacahoatán', 'Cacahoatán'),
	('Catazajá', 'Catazajá'),
	('Cintalapa', 'Cintalapa'),
	('Coapilla', 'Coapilla'),
	('Comitán de Domínguez', 'Comitán de Domínguez'),
	('La Concordia', 'La Concordia'),
	('Copainalá', 'Copainalá'),
	('Chalchihuitán', 'Chalchihuitán'),
	('Chamula', 'Chamula'),
	('Chanal', 'Chanal'),
	('Chapultenango', 'Chapultenango'),
	('Chenalhó', 'Chenalhó'),
	('Chiapa de Corzo', 'Chiapa de Corzo'),
	('Chiapilla', 'Chiapilla'),
	('Chicoasén', 'Chicoasén'),
	('Chicomuselo', 'Chicomuselo'),
	('Chilón', 'Chilón'),
	('Escuintla', 'Escuintla'),
	('Francisco León', 'Francisco León'),
	('Frontera Comalapa', 'Frontera Comalapa'),
	('Frontera Hidalgo', 'Frontera Hidalgo'),
	('La Grandeza', 'La Grandeza'),
	('Huehuetán', 'Huehuetán'),
	('Huixtán', 'Huixtán'),
	('Huitiupán', 'Huitiupán'),
	('Huixtla', 'Huixtla'),
	('La Independencia', 'La Independencia'),
	('Ixhuatán', 'Ixhuatán'),
	('Ixtacomitán', 'Ixtacomitán'),
	('Ixtapa', 'Ixtapa'),
	('Ixtapangajoya', 'Ixtapangajoya'),
	('Jiquipilas', 'Jiquipilas'),
	('Jitotol', 'Jitotol'),
	('Juárez', 'Juárez'),
	('Larráinzar', 'Larráinzar'),
	('La Libertad', 'La Libertad'),
	('Mapastepec', 'Mapastepec'),
	('Las Margaritas', 'Las Margaritas'),
	('Mazapa de Madero', 'Mazapa de Madero'),
	('Mazatán', 'Mazatán'),
	('Metapa', 'Metapa'),
	('Mitontic', 'Mitontic'),
	('Motozintla', 'Motozintla'),
	('Nicolás Ruíz', 'Nicolás Ruíz'),
	('Ocosingo', 'Ocosingo'),
	('Ocotepec', 'Ocotepec'),
	('Ocozocoautla de Espinosa', 'Ocozocoautla de Espinosa'),
	('Ostuacán', 'Ostuacán'),
	('Osumacinta', 'Osumacinta'),
	('Oxchuc', 'Oxchuc'),
	('Palenque', 'Palenque'),
	('Pantelhó', 'Pantelhó'),
	('Pantepec', 'Pantepec'),
	('Pichucalco', 'Pichucalco'),
	('Pijijiapan', 'Pijijiapan'),
	('El Porvenir', 'El Porvenir'),
	('Villa Comaltitlán', 'Villa Comaltitlán'),
	('Pueblo Nuevo Solistahuacán', 'Pueblo Nuevo Solistahuacán'),
	('Rayón', 'Rayón'),
	('Reforma', 'Reforma'),
	('Las Rosas', 'Las Rosas'),
	('Sabanilla', 'Sabanilla'),
	('Salto de Agua', 'Salto de Agua'),
	('San Cristóbal de las Casas', 'San Cristóbal de las Casas'),
	('San Fernando', 'San Fernando'),
	('Siltepec', 'Siltepec'),
	('Simojovel', 'Simojovel'),
	('Sitalá', 'Sitalá'),
	('Socoltenango', 'Socoltenango'),
	('Solosuchiapa', 'Solosuchiapa'),
	('Soyaló', 'Soyaló'),
	('Suchiapa', 'Suchiapa'),
	('Suchiate', 'Suchiate'),
	('Sunuapa', 'Sunuapa'),
	('Tapachula', 'Tapachula'),
	('Tapalapa', 'Tapalapa'),
	('Tapilula', 'Tapilula'),
	('Tecpatán', 'Tecpatán'),
	('Tenejapa', 'Tenejapa'),
	('Teopisca', 'Teopisca'),
	('Tila', 'Tila'),
	('Tonalá', 'Tonalá'),
	('Totolapa', 'Totolapa'),
	('La Trinitaria', 'La Trinitaria'),
	('Tumbalá', 'Tumbalá'),
	('Tuxtla Gutiérrez', 'Tuxtla Gutiérrez'),
	('Tuxtla Chico', 'Tuxtla Chico'),
	('Tuzantán', 'Tuzantán'),
	('Tzimol', 'Tzimol'),
	('Unión Juárez', 'Unión Juárez'),
	('Venustiano Carranza', 'Venustiano Carranza'),
	('Villa Corzo', 'Villa Corzo'),
	('Villaflores', 'Villaflores'),
	('Yajalón', 'Yajalón'),
	('San Lucas', 'San Lucas'),
	('Zinacantán', 'Zinacantán'),
	('San Juan Cancuc', 'San Juan Cancuc'),
	('Aldama', 'Aldama'),
	('Benemérito de las Américas', 'Benemérito de las Américas'),
	('Maravilla Tenejapa', 'Maravilla Tenejapa'),
	('Marqués de Comillas', 'Marqués de Comillas'),
	('Montecristo de Guerrero', 'Montecristo de Guerrero'),
	('San Andrés Duraznal', 'San Andrés Duraznal'),
	('Santiago el Pinar', 'Santiago el Pinar'),
	('Ahumada', 'Ahumada'),
	('Aldama', 'Aldama'),
	('Allende', 'Allende'),
	('Aquiles Serdán', 'Aquiles Serdán'),
	('Ascensión', 'Ascensión'),
	('Bachíniva', 'Bachíniva'),
	('Balleza', 'Balleza'),
	('Batopilas', 'Batopilas'),
	('Bocoyna', 'Bocoyna'),
	('Buenaventura', 'Buenaventura'),
	('Camargo', 'Camargo'),
	('Carichí', 'Carichí'),
	('Casas Grandes', 'Casas Grandes'),
	('Coronado', 'Coronado'),
	('Coyame del Sotol', 'Coyame del Sotol'),
	('La Cruz', 'La Cruz'),
	('Cuauhtémoc', 'Cuauhtémoc'),
	('Cusihuiriachi', 'Cusihuiriachi'),
	('Chihuahua', 'Chihuahua'),
	('Chínipas', 'Chínipas'),
	('Delicias', 'Delicias'),
	('Dr. Belisario Domínguez', 'Dr. Belisario Domínguez'),
	('Galeana', 'Galeana'),
	('Santa Isabel', 'Santa Isabel'),
	('Gómez Farías', 'Gómez Farías'),
	('Gran Morelos', 'Gran Morelos'),
	('Guachochi', 'Guachochi'),
	('Guadalupe', 'Guadalupe'),
	('Guadalupe y Calvo', 'Guadalupe y Calvo'),
	('Guazapares', 'Guazapares'),
	('Guerrero', 'Guerrero'),
	('Hidalgo del Parral', 'Hidalgo del Parral'),
	('Huejotitán', 'Huejotitán'),
	('Ignacio Zaragoza', 'Ignacio Zaragoza'),
	('Janos', 'Janos'),
	('Jiménez', 'Jiménez'),
	('Juárez', 'Juárez'),
	('Julimes', 'Julimes'),
	('López', 'López'),
	('Madera', 'Madera'),
	('Maguarichi', 'Maguarichi'),
	('Manuel Benavides', 'Manuel Benavides'),
	('Matachí', 'Matachí'),
	('Matamoros', 'Matamoros'),
	('Meoqui', 'Meoqui'),
	('Morelos', 'Morelos'),
	('Moris', 'Moris'),
	('Namiquipa', 'Namiquipa'),
	('Nonoava', 'Nonoava'),
	('Nuevo Casas Grandes', 'Nuevo Casas Grandes'),
	('Ocampo', 'Ocampo'),
	('Ojinaga', 'Ojinaga'),
	('Praxedis G. Guerrero', 'Praxedis G. Guerrero'),
	('Riva Palacio', 'Riva Palacio'),
	('Rosales', 'Rosales'),
	('Rosario', 'Rosario'),
	('San Francisco de Borja', 'San Francisco de Borja'),
	('San Francisco de Conchos', 'San Francisco de Conchos'),
	('San Francisco del Oro', 'San Francisco del Oro'),
	('Santa Bárbara', 'Santa Bárbara'),
	('Satevó', 'Satevó'),
	('Saucillo', 'Saucillo'),
	('Temósachic', 'Temósachic'),
	('El Tule', 'El Tule'),
	('Urique', 'Urique'),
	('Uruachi', 'Uruachi'),
	('Valle de Zaragoza', 'Valle de Zaragoza'),
	('Azcapotzalco', 'Azcapotzalco'),
	('Coyoacán', 'Coyoacán'),
	('Cuajimalpa de Morelos', 'Cuajimalpa de Morelos'),
	('Gustavo A. Madero', 'Gustavo A. Madero'),
	('Iztacalco', 'Iztacalco'),
	('Iztapalapa', 'Iztapalapa'),
	('La Magdalena Contreras', 'La Magdalena Contreras'),
	('Milpa Alta', 'Milpa Alta'),
	('Álvaro Obregón', 'Álvaro Obregón'),
	('Tláhuac', 'Tláhuac'),
	('Tlalpan', 'Tlalpan'),
	('Xochimilco', 'Xochimilco'),
	('Benito Juárez', 'Benito Juárez'),
	('Cuauhtémoc', 'Cuauhtémoc'),
	('Miguel Hidalgo', 'Miguel Hidalgo'),
	('Venustiano Carranza', 'Venustiano Carranza'),
	('Canatlán', 'Canatlán'),
	('Canelas', 'Canelas'),
	('Coneto de Comonfort', 'Coneto de Comonfort'),
	('Cuencamé', 'Cuencamé'),
	('Durango', 'Durango'),
	('General Simón Bolívar', 'General Simón Bolívar'),
	('Gómez Palacio', 'Gómez Palacio'),
	('Guadalupe Victoria', 'Guadalupe Victoria'),
	('Guanaceví', 'Guanaceví'),
	('Hidalgo', 'Hidalgo'),
	('Indé', 'Indé'),
	('Lerdo', 'Lerdo'),
	('Mapimí', 'Mapimí'),
	('Mezquital', 'Mezquital'),
	('Nazas', 'Nazas'),
	('Nombre de Dios', 'Nombre de Dios'),
	('Ocampo', 'Ocampo'),
	('El Oro', 'El Oro'),
	('Otáez', 'Otáez'),
	('Pánuco de Coronado', 'Pánuco de Coronado'),
	('Peñón Blanco', 'Peñón Blanco'),
	('Poanas', 'Poanas'),
	('Pueblo Nuevo', 'Pueblo Nuevo'),
	('Rodeo', 'Rodeo'),
	('San Bernardo', 'San Bernardo'),
	('San Dimas', 'San Dimas'),
	('San Juan de Guadalupe', 'San Juan de Guadalupe'),
	('San Juan del Río', 'San Juan del Río'),
	('San Luis del Cordero', 'San Luis del Cordero'),
	('San Pedro del Gallo', 'San Pedro del Gallo'),
	('Santa Clara', 'Santa Clara'),
	('Santiago Papasquiaro', 'Santiago Papasquiaro'),
	('Súchil', 'Súchil'),
	('Tamazula', 'Tamazula'),
	('Tepehuanes', 'Tepehuanes'),
	('Tlahualilo', 'Tlahualilo'),
	('Topia', 'Topia'),
	('Vicente Guerrero', 'Vicente Guerrero'),
	('Nuevo Ideal', 'Nuevo Ideal'),
	('Abasolo', 'Abasolo'),
	('Acámbaro', 'Acámbaro'),
	('San Miguel de Allende', 'San Miguel de Allende'),
	('Apaseo el Alto', 'Apaseo el Alto'),
	('Apaseo el Grande', 'Apaseo el Grande'),
	('Atarjea', 'Atarjea'),
	('Celaya', 'Celaya'),
	('Manuel Doblado', 'Manuel Doblado'),
	('Comonfort', 'Comonfort'),
	('Coroneo', 'Coroneo'),
	('Cortazar', 'Cortazar'),
	('Cuerámaro', 'Cuerámaro'),
	('Doctor Mora', 'Doctor Mora'),
	('Dolores Hidalgo Cuna de la Independencia Nacional', 'Dolores Hidalgo Cuna de la Independencia Nacional'),
	('Guanajuato', 'Guanajuato'),
	('Huanímaro', 'Huanímaro'),
	('Irapuato', 'Irapuato'),
	('Jaral del Progreso', 'Jaral del Progreso'),
	('Jerécuaro', 'Jerécuaro'),
	('León', 'León'),
	('Moroleón', 'Moroleón'),
	('Ocampo', 'Ocampo'),
	('Pénjamo', 'Pénjamo'),
	('Pueblo Nuevo', 'Pueblo Nuevo'),
	('Purísima del Rincón', 'Purísima del Rincón'),
	('Romita', 'Romita'),
	('Salamanca', 'Salamanca'),
	('Salvatierra', 'Salvatierra'),
	('San Diego de la Unión', 'San Diego de la Unión'),
	('San Felipe', 'San Felipe'),
	('San Francisco del Rincón', 'San Francisco del Rincón'),
	('San José Iturbide', 'San José Iturbide'),
	('San Luis de la Paz', 'San Luis de la Paz'),
	('Santa Catarina', 'Santa Catarina'),
	('Santa Cruz de Juventino Rosas', 'Santa Cruz de Juventino Rosas'),
	('Santiago Maravatío', 'Santiago Maravatío'),
	('Silao', 'Silao'),
	('Tarandacuao', 'Tarandacuao'),
	('Tarimoro', 'Tarimoro'),
	('Tierra Blanca', 'Tierra Blanca'),
	('Uriangato', 'Uriangato'),
	('Valle de Santiago', 'Valle de Santiago'),
	('Victoria', 'Victoria'),
	('Villagrán', 'Villagrán'),
	('Xichú', 'Xichú'),
	('Yuriri', 'Yuriri'),
	('Acapulco de Juárez', 'Acapulco de Juárez'),
	('Ahuacuotzingo', 'Ahuacuotzingo'),
	('Ajuchitlán del Progreso', 'Ajuchitlán del Progreso'),
	('Alcozauca de Guerrero', 'Alcozauca de Guerrero'),
	('Alpoyeca', 'Alpoyeca'),
	('Apaxtla', 'Apaxtla'),
	('Arcelia', 'Arcelia'),
	('Atenango del Río', 'Atenango del Río'),
	('Atlamajalcingo del Monte', 'Atlamajalcingo del Monte'),
	('Atlixtac', 'Atlixtac'),
	('Atoyac de Álvarez', 'Atoyac de Álvarez'),
	('Ayutla de los Libres', 'Ayutla de los Libres'),
	('Azoyú', 'Azoyú'),
	('Benito Juárez', 'Benito Juárez'),
	('Buenavista de Cuéllar', 'Buenavista de Cuéllar'),
	('Coahuayutla de José María Izazaga', 'Coahuayutla de José María Izazaga'),
	('Cocula', 'Cocula'),
	('Copala', 'Copala'),
	('Copalillo', 'Copalillo'),
	('Copanatoyac', 'Copanatoyac'),
	('Coyuca de Benítez', 'Coyuca de Benítez'),
	('Coyuca de Catalán', 'Coyuca de Catalán'),
	('Cuajinicuilapa', 'Cuajinicuilapa'),
	('Cualác', 'Cualác'),
	('Cuautepec', 'Cuautepec'),
	('Cuetzala del Progreso', 'Cuetzala del Progreso'),
	('Cutzamala de Pinzón', 'Cutzamala de Pinzón'),
	('Chilapa de Álvarez', 'Chilapa de Álvarez'),
	('Chilpancingo de los Bravo', 'Chilpancingo de los Bravo'),
	('Florencio Villarreal', 'Florencio Villarreal'),
	('General Canuto A. Neri', 'General Canuto A. Neri'),
	('General Heliodoro Castillo', 'General Heliodoro Castillo'),
	('Huamuxtitlán', 'Huamuxtitlán'),
	('Huitzuco de los Figueroa', 'Huitzuco de los Figueroa'),
	('Iguala de la Independencia', 'Iguala de la Independencia'),
	('Igualapa', 'Igualapa'),
	('Ixcateopan de Cuauhtémoc', 'Ixcateopan de Cuauhtémoc'),
	('Zihuatanejo de Azueta', 'Zihuatanejo de Azueta'),
	('Juan R. Escudero', 'Juan R. Escudero'),
	('Leonardo Bravo', 'Leonardo Bravo'),
	('Malinaltepec', 'Malinaltepec'),
	('Mártir de Cuilapan', 'Mártir de Cuilapan'),
	('Metlatónoc', 'Metlatónoc'),
	('Mochitlán', 'Mochitlán'),
	('Olinalá', 'Olinalá'),
	('Ometepec', 'Ometepec'),
	('Pedro Ascencio Alquisiras', 'Pedro Ascencio Alquisiras'),
	('Petatlán', 'Petatlán'),
	('Pilcaya', 'Pilcaya'),
	('Pungarabato', 'Pungarabato'),
	('Quechultenango', 'Quechultenango'),
	('San Luis Acatlán', 'San Luis Acatlán'),
	('San Marcos', 'San Marcos'),
	('San Miguel Totolapan', 'San Miguel Totolapan'),
	('Taxco de Alarcón', 'Taxco de Alarcón'),
	('Tecoanapa', 'Tecoanapa'),
	('Técpan de Galeana', 'Técpan de Galeana'),
	('Teloloapan', 'Teloloapan'),
	('Tepecoacuilco de Trujano', 'Tepecoacuilco de Trujano'),
	('Tetipac', 'Tetipac'),
	('Tixtla de Guerrero', 'Tixtla de Guerrero'),
	('Tlacoachistlahuaca', 'Tlacoachistlahuaca'),
	('Tlacoapa', 'Tlacoapa'),
	('Tlalchapa', 'Tlalchapa'),
	('Tlalixtaquilla de Maldonado', 'Tlalixtaquilla de Maldonado'),
	('Tlapa de Comonfort', 'Tlapa de Comonfort'),
	('Tlapehuala', 'Tlapehuala'),
	('La Unión de Isidoro Montes de Oca', 'La Unión de Isidoro Montes de Oca'),
	('Xalpatláhuac', 'Xalpatláhuac'),
	('Xochihuehuetlán', 'Xochihuehuetlán'),
	('Xochistlahuaca', 'Xochistlahuaca'),
	('Zapotitlán Tablas', 'Zapotitlán Tablas'),
	('Zirándaro', 'Zirándaro'),
	('Zitlala', 'Zitlala'),
	('Eduardo Neri', 'Eduardo Neri'),
	('Acatepec', 'Acatepec'),
	('Marquelia', 'Marquelia'),
	('Cochoapa el Grande', 'Cochoapa el Grande'),
	('José Joaquín de Herrera', 'José Joaquín de Herrera'),
	('Juchitán', 'Juchitán'),
	('Iliatenco', 'Iliatenco'),
	('Acatlán', 'Acatlán'),
	('Acaxochitlán', 'Acaxochitlán'),
	('Actopan', 'Actopan'),
	('Agua Blanca de Iturbide', 'Agua Blanca de Iturbide'),
	('Ajacuba', 'Ajacuba'),
	('Alfajayucan', 'Alfajayucan'),
	('Almoloya', 'Almoloya'),
	('Apan', 'Apan'),
	('El Arenal', 'El Arenal'),
	('Atitalaquia', 'Atitalaquia'),
	('Atlapexco', 'Atlapexco'),
	('Atotonilco el Grande', 'Atotonilco el Grande'),
	('Atotonilco de Tula', 'Atotonilco de Tula'),
	('Calnali', 'Calnali'),
	('Cardonal', 'Cardonal'),
	('Cuautepec de Hinojosa', 'Cuautepec de Hinojosa'),
	('Chapantongo', 'Chapantongo'),
	('Chapulhuacán', 'Chapulhuacán'),
	('Chilcuautla', 'Chilcuautla'),
	('Eloxochitlán', 'Eloxochitlán'),
	('Emiliano Zapata', 'Emiliano Zapata'),
	('Epazoyucan', 'Epazoyucan'),
	('Francisco I. Madero', 'Francisco I. Madero'),
	('Huasca de Ocampo', 'Huasca de Ocampo'),
	('Huautla', 'Huautla'),
	('Huazalingo', 'Huazalingo'),
	('Huehuetla', 'Huehuetla'),
	('Huejutla de Reyes', 'Huejutla de Reyes'),
	('Huichapan', 'Huichapan'),
	('Ixmiquilpan', 'Ixmiquilpan'),
	('Jacala de Ledezma', 'Jacala de Ledezma'),
	('Jaltocán', 'Jaltocán'),
	('Juárez Hidalgo', 'Juárez Hidalgo'),
	('Lolotla', 'Lolotla'),
	('Metepec', 'Metepec'),
	('San Agustín Metzquititlán', 'San Agustín Metzquititlán'),
	('Metztitlán', 'Metztitlán'),
	('Mineral del Chico', 'Mineral del Chico'),
	('Mineral del Monte', 'Mineral del Monte'),
	('La Misión', 'La Misión'),
	('Mixquiahuala de Juárez', 'Mixquiahuala de Juárez'),
	('Molango de Escamilla', 'Molango de Escamilla'),
	('Nicolás Flores', 'Nicolás Flores'),
	('Nopala de Villagrán', 'Nopala de Villagrán'),
	('Omitlán de Juárez', 'Omitlán de Juárez'),
	('San Felipe Orizatlán', 'San Felipe Orizatlán'),
	('Pacula', 'Pacula'),
	('Pachuca de Soto', 'Pachuca de Soto'),
	('Pisaflores', 'Pisaflores'),
	('Progreso de Obregón', 'Progreso de Obregón'),
	('Mineral de la Reforma', 'Mineral de la Reforma'),
	('San Agustín Tlaxiaca', 'San Agustín Tlaxiaca'),
	('San Bartolo Tutotepec', 'San Bartolo Tutotepec'),
	('San Salvador', 'San Salvador'),
	('Santiago de Anaya', 'Santiago de Anaya'),
	('Santiago Tulantepec de Lugo Guerrero', 'Santiago Tulantepec de Lugo Guerrero'),
	('Singuilucan', 'Singuilucan'),
	('Tasquillo', 'Tasquillo'),
	('Tecozautla', 'Tecozautla'),
	('Tenango de Doria', 'Tenango de Doria'),
	('Tepeapulco', 'Tepeapulco'),
	('Tepehuacán de Guerrero', 'Tepehuacán de Guerrero'),
	('Tepeji del Río de Ocampo', 'Tepeji del Río de Ocampo'),
	('Tepetitlán', 'Tepetitlán'),
	('Tetepango', 'Tetepango'),
	('Villa de Tezontepec', 'Villa de Tezontepec'),
	('Tezontepec de Aldama', 'Tezontepec de Aldama'),
	('Tianguistengo', 'Tianguistengo'),
	('Tizayuca', 'Tizayuca'),
	('Tlahuelilpan', 'Tlahuelilpan'),
	('Tlahuiltepa', 'Tlahuiltepa'),
	('Tlanalapa', 'Tlanalapa'),
	('Tlanchinol', 'Tlanchinol'),
	('Tlaxcoapan', 'Tlaxcoapan'),
	('Tolcayuca', 'Tolcayuca'),
	('Tula de Allende', 'Tula de Allende'),
	('Tulancingo de Bravo', 'Tulancingo de Bravo'),
	('Xochiatipan', 'Xochiatipan'),
	('Xochicoatlán', 'Xochicoatlán'),
	('Yahualica', 'Yahualica'),
	('Zacualtipán de Ángeles', 'Zacualtipán de Ángeles'),
	('Zapotlán de Juárez', 'Zapotlán de Juárez'),
	('Zempoala', 'Zempoala'),
	('Zimapán', 'Zimapán'),
	('Acatic', 'Acatic'),
	('Acatlán de Juárez', 'Acatlán de Juárez'),
	('Ahualulco de Mercado', 'Ahualulco de Mercado'),
	('Amacueca', 'Amacueca'),
	('Amatitán', 'Amatitán'),
	('Ameca', 'Ameca'),
	('San Juanito de Escobedo', 'San Juanito de Escobedo'),
	('Arandas', 'Arandas'),
	('El Arenal', 'El Arenal'),
	('Atemajac de Brizuela', 'Atemajac de Brizuela'),
	('Atengo', 'Atengo'),
	('Atenguillo', 'Atenguillo'),
	('Atotonilco el Alto', 'Atotonilco el Alto'),
	('Atoyac', 'Atoyac'),
	('Autlán de Navarro', 'Autlán de Navarro'),
	('Ayotlán', 'Ayotlán'),
	('Ayutla', 'Ayutla'),
	('La Barca', 'La Barca'),
	('Bolaños', 'Bolaños'),
	('Cabo Corrientes', 'Cabo Corrientes'),
	('Casimiro Castillo', 'Casimiro Castillo'),
	('Cihuatlán', 'Cihuatlán'),
	('Zapotlán el Grande', 'Zapotlán el Grande'),
	('Cocula', 'Cocula'),
	('Colotlán', 'Colotlán'),
	('Concepción de Buenos Aires', 'Concepción de Buenos Aires'),
	('Cuautitlán de García Barragán', 'Cuautitlán de García Barragán'),
	('Cuautla', 'Cuautla'),
	('Cuquío', 'Cuquío'),
	('Chapala', 'Chapala'),
	('Chimaltitán', 'Chimaltitán'),
	('Chiquilistlán', 'Chiquilistlán'),
	('Degollado', 'Degollado'),
	('Ejutla', 'Ejutla'),
	('Encarnación de Díaz', 'Encarnación de Díaz'),
	('Etzatlán', 'Etzatlán'),
	('El Grullo', 'El Grullo'),
	('Guachinango', 'Guachinango'),
	('Guadalajara', 'Guadalajara'),
	('Hostotipaquillo', 'Hostotipaquillo'),
	('Huejúcar', 'Huejúcar'),
	('Huejuquilla el Alto', 'Huejuquilla el Alto'),
	('La Huerta', 'La Huerta'),
	('Ixtlahuacán de los Membrillos', 'Ixtlahuacán de los Membrillos'),
	('Ixtlahuacán del Río', 'Ixtlahuacán del Río'),
	('Jalostotitlán', 'Jalostotitlán'),
	('Jamay', 'Jamay'),
	('Jesús María', 'Jesús María'),
	('Jilotlán de los Dolores', 'Jilotlán de los Dolores'),
	('Jocotepec', 'Jocotepec'),
	('Juanacatlán', 'Juanacatlán'),
	('Juchitlán', 'Juchitlán'),
	('Lagos de Moreno', 'Lagos de Moreno'),
	('El Limón', 'El Limón'),
	('Magdalena', 'Magdalena'),
	('Santa María del Oro', 'Santa María del Oro'),
	('La Manzanilla de la Paz', 'La Manzanilla de la Paz'),
	('Mascota', 'Mascota'),
	('Mazamitla', 'Mazamitla'),
	('Mexticacán', 'Mexticacán'),
	('Mezquitic', 'Mezquitic'),
	('Mixtlán', 'Mixtlán'),
	('Ocotlán', 'Ocotlán'),
	('Ojuelos de Jalisco', 'Ojuelos de Jalisco'),
	('Pihuamo', 'Pihuamo'),
	('Poncitlán', 'Poncitlán'),
	('Puerto Vallarta', 'Puerto Vallarta'),
	('Villa Purificación', 'Villa Purificación'),
	('Quitupan', 'Quitupan'),
	('El Salto', 'El Salto'),
	('San Cristóbal de la Barranca', 'San Cristóbal de la Barranca'),
	('San Diego de Alejandría', 'San Diego de Alejandría'),
	('San Juan de los Lagos', 'San Juan de los Lagos'),
	('San Julián', 'San Julián'),
	('San Marcos', 'San Marcos'),
	('	San Martín de Bolaños', '	San Martín de Bolaños'),
	('San Martín Hidalgo', 'San Martín Hidalgo'),
	('San Miguel el Alto', 'San Miguel el Alto'),
	('Gómez Farías', 'Gómez Farías'),
	('San Sebastián del Oeste', 'San Sebastián del Oeste'),
	('Santa María de los Ángeles', 'Santa María de los Ángeles'),
	('Sayula', 'Sayula'),
	('Tala', 'Tala'),
	('Talpa de Allende', 'Talpa de Allende'),
	('Tamazula de Gordiano', 'Tamazula de Gordiano'),
	('Tapalpa', 'Tapalpa'),
	('Tecalitlán', 'Tecalitlán'),
	('Tecolotlán', 'Tecolotlán'),
	('Techaluta de Montenegro', 'Techaluta de Montenegro'),
	('Tenamaxtlán', 'Tenamaxtlán'),
	('Teocaltiche', 'Teocaltiche'),
	('Teocuitatlán de Corona', 'Teocuitatlán de Corona'),
	('Tepatitlán de Morelos', 'Tepatitlán de Morelos'),
	('Tequila', 'Tequila'),
	('Teuchitlán', 'Teuchitlán'),
	('Tizapán el Alto', 'Tizapán el Alto'),
	('Tlajomulco de Zúñiga', 'Tlajomulco de Zúñiga'),
	('San Pedro Tlaquepaque', 'San Pedro Tlaquepaque'),
	('Tolimán', 'Tolimán'),
	('Tomatlán', 'Tomatlán'),
	('Tonalá', 'Tonalá'),
	('Tonaya', 'Tonaya'),
	('Tonila', 'Tonila'),
	('Totatiche', 'Totatiche'),
	('Tototlán', 'Tototlán'),
	('Tuxcacuesco', 'Tuxcacuesco'),
	('Tuxcueca', 'Tuxcueca'),
	('Tuxpan', 'Tuxpan'),
	('Unión de San Antonio', 'Unión de San Antonio'),
	('Unión de Tula', 'Unión de Tula'),
	('Valle de Guadalupe', 'Valle de Guadalupe'),
	('Valle de Juárez', 'Valle de Juárez'),
	('San Gabriel', 'San Gabriel'),
	('Villa Corona', 'Villa Corona'),
	('Villa Guerrero', 'Villa Guerrero'),
	('Villa Hidalgo', 'Villa Hidalgo'),
	('Cañadas de Obregón', 'Cañadas de Obregón'),
	('Yahualica de González Gallo', 'Yahualica de González Gallo'),
	('Zacoalco de Torres', 'Zacoalco de Torres'),
	('Zapopan', 'Zapopan'),
	('Zapotiltic', 'Zapotiltic'),
	('Zapotitlán de Vadillo', 'Zapotitlán de Vadillo'),
	('Zapotlán del Rey', 'Zapotlán del Rey'),
	('Zapotlanejo', 'Zapotlanejo'),
	('San Ignacio Cerro Gordo', 'San Ignacio Cerro Gordo'),
	('Acambay de Ruíz Castañeda', 'Acambay de Ruíz Castañeda'),
	('Acolman', 'Acolman'),
	('Aculco', 'Aculco'),
	('Almoloya de Alquisiras', 'Almoloya de Alquisiras'),
	('Almoloya de Juárez', 'Almoloya de Juárez'),
	('Almoloya del Río', 'Almoloya del Río'),
	('Amanalco', 'Amanalco'),
	('Amatepec', 'Amatepec'),
	('Amecameca', 'Amecameca'),
	('Apaxco', 'Apaxco'),
	('Atenco', 'Atenco'),
	('Atizapán', 'Atizapán'),
	('Atizapán de Zaragoza', 'Atizapán de Zaragoza'),
	('Atlacomulco', 'Atlacomulco'),
	('Atlautla', 'Atlautla'),
	('Axapusco', 'Axapusco'),
	('Ayapango', 'Ayapango'),
	('Calimaya', 'Calimaya'),
	('Capulhuac', 'Capulhuac'),
	('Coacalco de Berriozábal', 'Coacalco de Berriozábal'),
	('Coatepec Harinas', 'Coatepec Harinas'),
	('Cocotitlán', 'Cocotitlán'),
	('Coyotepec', 'Coyotepec'),
	('Cuautitlán', 'Cuautitlán'),
	('Chalco', 'Chalco'),
	('Chapa de Mota', 'Chapa de Mota'),
	('Chapultepec', 'Chapultepec'),
	('Chiautla', 'Chiautla'),
	('Chicoloapan', 'Chicoloapan'),
	('Chiconcuac', 'Chiconcuac'),
	('Chimalhuacán', 'Chimalhuacán'),
	('Donato Guerra', 'Donato Guerra'),
	('Ecatepec de Morelos', 'Ecatepec de Morelos'),
	('Ecatzingo', 'Ecatzingo'),
	('Huehuetoca', 'Huehuetoca'),
	('Hueypoxtla', 'Hueypoxtla'),
	('Huixquilucan', 'Huixquilucan'),
	('Isidro Fabela', 'Isidro Fabela'),
	('Ixtapaluca', 'Ixtapaluca'),
	('Ixtapan de la Sal', 'Ixtapan de la Sal'),
	('Ixtapan del Oro', 'Ixtapan del Oro'),
	('Ixtlahuaca', 'Ixtlahuaca'),
	('Jalatlaco', 'Jalatlaco'),
	('Jaltenco', 'Jaltenco'),
	('Jilotepec', 'Jilotepec'),
	('Jilotzingo', 'Jilotzingo'),
	('Jiquipilco', 'Jiquipilco'),
	('Jocotitlán', 'Jocotitlán'),
	('Joquicingo', 'Joquicingo'),
	('Juchitepec', 'Juchitepec'),
	('Lerma', 'Lerma'),
	('Malinalco', 'Malinalco'),
	('Melchor Ocampo', 'Melchor Ocampo'),
	('Metepec', 'Metepec'),
	('Mexicaltzingo', 'Mexicaltzingo'),
	('Morelos', 'Morelos'),
	('Naucalpan de Juárez', 'Naucalpan de Juárez'),
	('Nezahualcóyotl', 'Nezahualcóyotl'),
	('Nextlalpan', 'Nextlalpan'),
	('Nicolás Romero', 'Nicolás Romero'),
	('Nopaltepec', 'Nopaltepec'),
	('Ocoyoacac', 'Ocoyoacac'),
	('Ocuilan', 'Ocuilan'),
	('El Oro', 'El Oro'),
	('Otumba', 'Otumba'),
	('Otzoloapan', 'Otzoloapan'),
	('Otzolotepec', 'Otzolotepec'),
	('Ozumba', 'Ozumba'),
	('Papalotla', 'Papalotla'),
	('La Paz', 'La Paz'),
	('Polotitlán', 'Polotitlán'),
	('Rayón', 'Rayón'),
	('San Antonio la Isla', 'San Antonio la Isla'),
	('San Felipe del Progreso', 'San Felipe del Progreso'),
	('San Martín de las Pirámides', 'San Martín de las Pirámides'),
	('San Mateo Atenco', 'San Mateo Atenco'),
	('San Simón de Guerrero', 'San Simón de Guerrero'),
	('Santo Tomás', 'Santo Tomás'),
	('Soyaniquilpan de Juárez', 'Soyaniquilpan de Juárez'),
	('Sultepec', 'Sultepec'),
	('Tecámac', 'Tecámac'),
	('Tejupilco', 'Tejupilco'),
	('Temamatla', 'Temamatla'),
	('Temascalapa', 'Temascalapa'),
	('Temascalcingo', 'Temascalcingo'),
	('Temascaltepec', 'Temascaltepec'),
	('Temoaya', 'Temoaya'),
	('Tenancingo', 'Tenancingo'),
	('Tenango del Aire', 'Tenango del Aire'),
	('Tenango del Valle', 'Tenango del Valle'),
	('Teoloyucan', 'Teoloyucan'),
	('Teotihuacán', 'Teotihuacán'),
	('Tepetlaoxtoc', 'Tepetlaoxtoc'),
	('Tepetlixpa', 'Tepetlixpa'),
	('Tepotzotlán', 'Tepotzotlán'),
	('Tequixquiac', 'Tequixquiac'),
	('Texcaltitlán', 'Texcaltitlán'),
	('Texcalyacac', 'Texcalyacac'),
	('Texcoco', 'Texcoco'),
	('Tezoyuca', 'Tezoyuca'),
	('Tianguistenco', 'Tianguistenco'),
	('Timilpan', 'Timilpan'),
	('Tlalmanalco', 'Tlalmanalco'),
	('Tlalnepantla de Baz', 'Tlalnepantla de Baz'),
	('Tlatlaya', 'Tlatlaya'),
	('Toluca', 'Toluca'),
	('Tonatico', 'Tonatico'),
	('Tultepec', 'Tultepec'),
	('Tultitlán', 'Tultitlán'),
	('Valle de Bravo', 'Valle de Bravo'),
	('Villa de Allende', 'Villa de Allende'),
	('Villa del Carbón', 'Villa del Carbón'),
	('Villa Guerrero', 'Villa Guerrero'),
	('Villa Victoria', 'Villa Victoria'),
	('Xonacatlán', 'Xonacatlán'),
	('Zacazonapan', 'Zacazonapan'),
	('Zacualpan', 'Zacualpan'),
	('Zinacantepec', 'Zinacantepec'),
	('Zumpahuacán', 'Zumpahuacán'),
	('Zumpango', 'Zumpango'),
	('Cuautitlán Izcalli', 'Cuautitlán Izcalli'),
	('Valle de Chalco Solidaridad', 'Valle de Chalco Solidaridad'),
	('Luvianos', 'Luvianos'),
	('San José del Rincón', 'San José del Rincón'),
	('Tonanitla', 'Tonanitla'),
	('Acuitzio', 'Acuitzio'),
	('Aguililla', 'Aguililla'),
	('Álvaro Obregón', 'Álvaro Obregón'),
	('Angamacutiro', 'Angamacutiro'),
	('Angangueo', 'Angangueo'),
	('Apatzingán', 'Apatzingán'),
	('Aporo', 'Aporo'),
	('Aquila', 'Aquila'),
	('Ario', 'Ario'),
	('Arteaga', 'Arteaga'),
	('Briseñas', 'Briseñas'),
	('Buenavista', 'Buenavista'),
	('Carácuaro', 'Carácuaro'),
	('Coahuayana', 'Coahuayana'),
	('Coalcomán de Vázquez Pallares', 'Coalcomán de Vázquez Pallares'),
	('Coeneo', 'Coeneo'),
	('Contepec', 'Contepec'),
	('Copándaro', 'Copándaro'),
	('Cotija', 'Cotija'),
	('Cuitzeo', 'Cuitzeo'),
	('Charapan', 'Charapan'),
	('Charo', 'Charo'),
	('Chavinda', 'Chavinda'),
	('Cherán', 'Cherán'),
	('Chilchota', 'Chilchota'),
	('Chinicuila', 'Chinicuila'),
	('Chucándiro', 'Chucándiro'),
	('Churintzio', 'Churintzio'),
	('Churumuco', 'Churumuco'),
	('Ecuandureo', 'Ecuandureo'),
	('Epitacio Huerta', 'Epitacio Huerta'),
	('Erongarícuaro', 'Erongarícuaro'),
	('Gabriel Zamora', 'Gabriel Zamora'),
	('Hidalgo', 'Hidalgo'),
	('La Huacana', 'La Huacana'),
	('Huandacareo', 'Huandacareo'),
	('Huaniqueo', 'Huaniqueo'),
	('Huetamo', 'Huetamo'),
	('Huiramba', 'Huiramba'),
	('Indaparapeo', 'Indaparapeo'),
	('Irimbo', 'Irimbo'),
	('Ixtlán', 'Ixtlán'),
	('Jacona', 'Jacona'),
	('Jiménez', 'Jiménez'),
	('Jiquilpan', 'Jiquilpan'),
	('Juárez', 'Juárez'),
	('Jungapeo', 'Jungapeo'),
	('Lagunillas', 'Lagunillas'),
	('Madero', 'Madero'),
	('Maravatío', 'Maravatío'),
	('Marcos Castellanos', 'Marcos Castellanos'),
	('Lázaro Cárdenas', 'Lázaro Cárdenas'),
	('Morelia', 'Morelia'),
	('Morelos', 'Morelos'),
	('Múgica', 'Múgica'),
	('Nahuatzen', 'Nahuatzen'),
	('Nocupétaro', 'Nocupétaro'),
	('Nuevo Parangaricutiro', 'Nuevo Parangaricutiro'),
	('Nuevo Urecho', 'Nuevo Urecho'),
	('Numarán', 'Numarán'),
	('Ocampo', 'Ocampo'),
	('Pajacuarán', 'Pajacuarán'),
	('Panindícuaro', 'Panindícuaro'),
	('Parácuaro', 'Parácuaro'),
	('Paracho', 'Paracho'),
	('Pátzcuaro', 'Pátzcuaro'),
	('Penjamillo', 'Penjamillo'),
	('Peribán', 'Peribán'),
	('La Piedad', 'La Piedad'),
	('Purépero', 'Purépero'),
	('Puruándiro', 'Puruándiro'),
	('Queréndaro', 'Queréndaro'),
	('Quiroga', 'Quiroga'),
	('Cojumatlán de Régules', 'Cojumatlán de Régules'),
	('Los Reyes', 'Los Reyes'),
	('Sahuayo', 'Sahuayo'),
	('San Lucas', 'San Lucas'),
	('Santa Ana Maya', 'Santa Ana Maya'),
	('Salvador Escalante', 'Salvador Escalante'),
	('Senguio', 'Senguio'),
	('Susupuato', 'Susupuato'),
	('Tacámbaro', 'Tacámbaro'),
	('Tancítaro', 'Tancítaro'),
	('Tangamandapio', 'Tangamandapio'),
	('Tangancícuaro', 'Tangancícuaro'),
	('Tanhuato', 'Tanhuato'),
	('Taretan', 'Taretan'),
	('Tarímbaro', 'Tarímbaro'),
	('Tepalcatepec', 'Tepalcatepec'),
	('Tingambato', 'Tingambato'),
	('Tinguindín', 'Tinguindín'),
	('Tiquicheo de Nicolás Romero', 'Tiquicheo de Nicolás Romero'),
	('Tlalpujahua', 'Tlalpujahua'),
	('Tlazazalca', 'Tlazazalca'),
	('Tocumbo', 'Tocumbo'),
	('Tumbiscatío', 'Tumbiscatío'),
	('Turicato', 'Turicato'),
	('Tuxpan', 'Tuxpan'),
	('Tuzantla', 'Tuzantla'),
	('Tzintzuntzan', 'Tzintzuntzan'),
	('Tzitzio', 'Tzitzio'),
	('Uruapan', 'Uruapan'),
	('Venustiano Carranza', 'Venustiano Carranza'),
	('Villamar', 'Villamar'),
	('Vista Hermosa', 'Vista Hermosa'),
	('Yurécuaro', 'Yurécuaro'),
	('Zacapu', 'Zacapu'),
	('Zamora', 'Zamora'),
	('Zináparo', 'Zináparo'),
	('Zinapécuaro', 'Zinapécuaro'),
	('Ziracuaretiro', 'Ziracuaretiro'),
	('Zitácuaro', 'Zitácuaro'),
	('José Sixto Verduzco', 'José Sixto Verduzco'),
	('Amacuzac', 'Amacuzac'),
	('Atlatlahucan', 'Atlatlahucan'),
	('Axochiapan', 'Axochiapan'),
	('Ayala', 'Ayala'),
	('Coatlán del Río', 'Coatlán del Río'),
	('Cuautla', 'Cuautla'),
	('Cuernavaca', 'Cuernavaca'),
	('Emiliano Zapata', 'Emiliano Zapata'),
	('Huitzilac', 'Huitzilac'),
	('Jantetelco', 'Jantetelco'),
	('Jiutepec', 'Jiutepec'),
	('Jojutla', 'Jojutla'),
	('Jonacatepec', 'Jonacatepec'),
	('Mazatepec', 'Mazatepec'),
	('Miacatlán', 'Miacatlán'),
	('Ocuituco', 'Ocuituco'),
	('Puente de Ixtla', 'Puente de Ixtla'),
	('Temixco', 'Temixco'),
	('Tepalcingo', 'Tepalcingo'),
	('Tepoztlán', 'Tepoztlán'),
	('Tetecala', 'Tetecala'),
	('Tetela del Volcán', 'Tetela del Volcán'),
	('Tlalnepantla', 'Tlalnepantla'),
	('Tlaltizapán de Zapata', 'Tlaltizapán de Zapata'),
	('Tlaquiltenango', 'Tlaquiltenango'),
	('Tlayacapan', 'Tlayacapan'),
	('Totolapan', 'Totolapan'),
	('Xochitepec', 'Xochitepec'),
	('Yautepec', 'Yautepec'),
	('Yecapixtla', 'Yecapixtla'),
	('Zacatepec', 'Zacatepec'),
	('Zacualpan', 'Zacualpan'),
	('Temoac', 'Temoac'),
	('Acaponeta', 'Acaponeta'),
	('Ahuacatlán', 'Ahuacatlán'),
	('Amatlán de Cañas', 'Amatlán de Cañas'),
	('Compostela', 'Compostela'),
	('Huajicori', 'Huajicori'),
	('Ixtlán del Río', 'Ixtlán del Río'),
	('Jala', 'Jala'),
	('Xalisco', 'Xalisco'),
	('Del Nayar', 'Del Nayar'),
	('Rosamorada', 'Rosamorada'),
	('Ruíz', 'Ruíz'),
	('San Blas', 'San Blas'),
	('San Pedro Lagunillas', 'San Pedro Lagunillas'),
	('Santa María del Oro', 'Santa María del Oro'),
	('Santiago Ixcuintla', 'Santiago Ixcuintla'),
	('Tecuala', 'Tecuala'),
	('Tepic', 'Tepic'),
	('Tuxpan', 'Tuxpan'),
	('La Yesca', 'La Yesca'),
	('Bahía de Banderas', 'Bahía de Banderas'),
	('Abasolo', 'Abasolo'),
	('Agualeguas', 'Agualeguas'),
	('Los Aldamas', 'Los Aldamas'),
	('Allende', 'Allende'),
	('Anáhuac', 'Anáhuac'),
	('Apodaca', 'Apodaca'),
	('Aramberri', 'Aramberri'),
	('Bustamante', 'Bustamante'),
	('Cadereyta Jiménez', 'Cadereyta Jiménez'),
	('El Carmen', 'El Carmen'),
	('Cerralvo', 'Cerralvo'),
	('Ciénega de Flores', 'Ciénega de Flores'),
	('China', 'China'),
	('Doctor Arroyo', 'Doctor Arroyo'),
	('Doctor Coss', 'Doctor Coss'),
	('Doctor González', 'Doctor González'),
	('Galeana', 'Galeana'),
	('García', 'García'),
	('San Pedro Garza García', 'San Pedro Garza García'),
	('General Bravo', 'General Bravo'),
	('General Escobedo', 'General Escobedo'),
	('General Terán', 'General Terán'),
	('General Treviño', 'General Treviño'),
	('General Zaragoza', 'General Zaragoza'),
	('General Zuazua', 'General Zuazua'),
	('Guadalupe', 'Guadalupe'),
	('Los Herreras', 'Los Herreras'),
	('Higueras', 'Higueras'),
	('Hualahuises', 'Hualahuises'),
	('Iturbide', 'Iturbide'),
	('Juárez', 'Juárez'),
	('Lampazos de Naranjo', 'Lampazos de Naranjo'),
	('Linares', 'Linares'),
	('Marín', 'Marín'),
	('Melchor Ocampo', 'Melchor Ocampo'),
	('Mier y Noriega', 'Mier y Noriega'),
	('Mina', 'Mina'),
	('Montemorelos', 'Montemorelos'),
	('Monterrey', 'Monterrey'),
	('Parás', 'Parás'),
	('Pesquería', 'Pesquería'),
	('Los Ramones', 'Los Ramones'),
	('Rayones', 'Rayones'),
	('Sabinas Hidalgo', 'Sabinas Hidalgo'),
	('Salinas Victoria', 'Salinas Victoria'),
	('San Nicolás de los Garza', 'San Nicolás de los Garza'),
	('Hidalgo', 'Hidalgo'),
	('Santa Catarina', 'Santa Catarina'),
	('Santiago', 'Santiago'),
	('Vallecillo', 'Vallecillo'),
	('Villaldama', 'Villaldama'),
	('Abejones', 'Abejones'),
	('Acatlán de Pérez Figueroa', 'Acatlán de Pérez Figueroa'),
	('Asunción Cacalotepec', 'Asunción Cacalotepec'),
	('Asunción Cuyotepeji', 'Asunción Cuyotepeji'),
	('Asunción Ixtaltepec', 'Asunción Ixtaltepec'),
	('Asunción Nochixtlán', 'Asunción Nochixtlán'),
	('Asunción Ocotlán', 'Asunción Ocotlán'),
	('Asunción Tlacolulita', 'Asunción Tlacolulita'),
	('Ayotzintepec', 'Ayotzintepec'),
	('El Barrio de la Soledad', 'El Barrio de la Soledad'),
	('Calihualá', 'Calihualá'),
	('Candelaria Loxicha', 'Candelaria Loxicha'),
	('Ciénega de Zimatlán', 'Ciénega de Zimatlán'),
	('Ciudad Ixtepec', 'Ciudad Ixtepec'),
	('Coatecas Altas', 'Coatecas Altas'),
	('Coicoyán de las Flores', 'Coicoyán de las Flores'),
	('La Compañía', 'La Compañía'),
	('Concepción Buenavista', 'Concepción Buenavista'),
	('Concepción Pápalo', 'Concepción Pápalo'),
	('Constancia del Rosario', 'Constancia del Rosario'),
	('Cosolapa', 'Cosolapa'),
	('Cosoltepec', 'Cosoltepec'),
	('Cuilápam de Guerrero', 'Cuilápam de Guerrero'),
	('Cuyamecalco Villa de Zaragoza', 'Cuyamecalco Villa de Zaragoza'),
	('Chahuites', 'Chahuites'),
	('Chalcatongo de Hidalgo', 'Chalcatongo de Hidalgo'),
	('Chiquihuitlán de Benito Juárez', 'Chiquihuitlán de Benito Juárez'),
	('Heroica Ciudad de Ejutla de Crespo', 'Heroica Ciudad de Ejutla de Crespo'),
	('Eloxochitlán de Flores Magón', 'Eloxochitlán de Flores Magón'),
	('El Espinal', 'El Espinal'),
	('Tamazulápam del Espíritu Santo', 'Tamazulápam del Espíritu Santo'),
	('Fresnillo de Trujano', 'Fresnillo de Trujano'),
	('Guadalupe Etla', 'Guadalupe Etla'),
	('Guadalupe de Ramírez', 'Guadalupe de Ramírez'),
	('Guelatao de Juárez', 'Guelatao de Juárez'),
	('Guevea de Humboldt', 'Guevea de Humboldt'),
	('Mesones Hidalgo', 'Mesones Hidalgo'),
	('Villa Hidalgo', 'Villa Hidalgo'),
	('Heroica Ciudad de Huajuapan de León', 'Heroica Ciudad de Huajuapan de León'),
	('Huautepec', 'Huautepec'),
	('Huautla de Jiménez', 'Huautla de Jiménez'),
	('Ixtlán de Juárez', 'Ixtlán de Juárez'),
	('Heroica Ciudad de Juchitán de Zaragoza', 'Heroica Ciudad de Juchitán de Zaragoza'),
	('Loma Bonita', 'Loma Bonita'),
	('Magdalena Apasco', 'Magdalena Apasco'),
	('Magdalena Jaltepec', 'Magdalena Jaltepec'),
	('Santa Magdalena Jicotlán', 'Santa Magdalena Jicotlán'),
	('Magdalena Mixtepec', 'Magdalena Mixtepec'),
	('Magdalena Ocotlán', 'Magdalena Ocotlán'),
	('Magdalena Peñasco', 'Magdalena Peñasco'),
	('Magdalena Teitipac', 'Magdalena Teitipac'),
	('Magdalena Tequisistlán', 'Magdalena Tequisistlán'),
	('Magdalena Tlacotepec', 'Magdalena Tlacotepec'),
	('Magdalena Zahuatlán', 'Magdalena Zahuatlán'),
	('Mariscala de Juárez', 'Mariscala de Juárez'),
	('Mártires de Tacubaya', 'Mártires de Tacubaya'),
	('Matías Romero Avendaño', 'Matías Romero Avendaño'),
	('Mazatlán Villa de Flores', 'Mazatlán Villa de Flores'),
	('Miahuatlán de Porfirio Díaz', 'Miahuatlán de Porfirio Díaz'),
	('Mixistlán de la Reforma', 'Mixistlán de la Reforma'),
	('Monjas', 'Monjas'),
	('Natividad', 'Natividad'),
	('Nazareno Etla', 'Nazareno Etla'),
	('Nejapa de Madero', 'Nejapa de Madero'),
	('Ixpantepec Nieves', 'Ixpantepec Nieves'),
	('Santiago Niltepec', 'Santiago Niltepec'),
	('Oaxaca de Juárez', 'Oaxaca de Juárez'),
	('Ocotlán de Morelos', 'Ocotlán de Morelos'),
	('La Pe', 'La Pe'),
	('Pinotepa de Don Luis', 'Pinotepa de Don Luis'),
	('Pluma Hidalgo', 'Pluma Hidalgo'),
	('San José del Progreso', 'San José del Progreso'),
	('Putla Villa de Guerrero', 'Putla Villa de Guerrero'),
	('Santa Catarina Quioquitani', 'Santa Catarina Quioquitani'),
	('Reforma de Pineda', 'Reforma de Pineda'),
	('La Reforma', 'La Reforma'),
	('Reyes Etla', 'Reyes Etla'),
	('Rojas de Cuauhtémoc', 'Rojas de Cuauhtémoc'),
	('Salina Cruz', 'Salina Cruz'),
	('San Agustín Amatengo', 'San Agustín Amatengo'),
	('San Agustín Atenango', 'San Agustín Atenango'),
	('San Agustín Chayuco', 'San Agustín Chayuco'),
	('San Agustín de las Juntas', 'San Agustín de las Juntas'),
	('San Agustín Etla', 'San Agustín Etla'),
	('San Agustín Loxicha', 'San Agustín Loxicha'),
	('San Agustín Tlacotepec', 'San Agustín Tlacotepec'),
	('San Agustín Yatareni', 'San Agustín Yatareni'),
	('San Andrés Cabecera Nueva', 'San Andrés Cabecera Nueva'),
	('San Andrés Dinicuiti', 'San Andrés Dinicuiti'),
	('San Andrés Huaxpaltepec', 'San Andrés Huaxpaltepec'),
	('San Andrés Huayápam', 'San Andrés Huayápam'),
	('San Andrés Ixtlahuaca', 'San Andrés Ixtlahuaca'),
	('San Andrés Lagunas', 'San Andrés Lagunas'),
	('San Andrés Nuxiño', 'San Andrés Nuxiño'),
	('San Andrés Paxtlán', 'San Andrés Paxtlán'),
	('San Andrés Sinaxtla', 'San Andrés Sinaxtla'),
	('San Andrés Solaga', 'San Andrés Solaga'),
	('San Andrés Teotilálpam', 'San Andrés Teotilálpam'),
	('San Andrés Tepetlapa', 'San Andrés Tepetlapa'),
	('San Andrés Yaá', 'San Andrés Yaá'),
	('San Andrés Zabache', 'San Andrés Zabache'),
	('San Andrés Zautla', 'San Andrés Zautla'),
	('San Antonino Castillo Velasco', 'San Antonino Castillo Velasco'),
	('San Antonino el Alto', 'San Antonino el Alto'),
	('San Antonino Monte Verde', 'San Antonino Monte Verde'),
	('San Antonio Acutla', 'San Antonio Acutla'),
	('San Antonio de la Cal', 'San Antonio de la Cal'),
	('San Antonio Huitepec', 'San Antonio Huitepec'),
	('San Antonio Nanahuatípam', 'San Antonio Nanahuatípam'),
	('San Antonio Sinicahua', 'San Antonio Sinicahua'),
	('San Antonio Tepetlapa', 'San Antonio Tepetlapa'),
	('San Baltazar Chichicápam', 'San Baltazar Chichicápam'),
	('San Baltazar Loxicha', 'San Baltazar Loxicha'),
	('San Baltazar Yatzachi el Bajo', 'San Baltazar Yatzachi el Bajo'),
	('San Bartolo Coyotepec', 'San Bartolo Coyotepec'),
	('San Bartolomé Ayautla', 'San Bartolomé Ayautla'),
	('San Bartolomé Loxicha', 'San Bartolomé Loxicha'),
	('San Bartolomé Quialana', 'San Bartolomé Quialana'),
	('San Bartolomé Yucuañe', 'San Bartolomé Yucuañe'),
	('San Bartolomé Zoogocho', 'San Bartolomé Zoogocho'),
	('San Bartolo Soyaltepec', 'San Bartolo Soyaltepec'),
	('San Bartolo Yautepec', 'San Bartolo Yautepec'),
	('San Bernardo Mixtepec', 'San Bernardo Mixtepec'),
	('San Blas Atempa', 'San Blas Atempa'),
	('San Carlos Yautepec', 'San Carlos Yautepec'),
	('San Cristóbal Amatlán', 'San Cristóbal Amatlán'),
	('San Cristóbal Amoltepec', 'San Cristóbal Amoltepec'),
	('San Cristóbal Lachirioag', 'San Cristóbal Lachirioag'),
	('San Cristóbal Suchixtlahuaca', 'San Cristóbal Suchixtlahuaca'),
	('San Dionisio del Mar', 'San Dionisio del Mar'),
	('San Dionisio Ocotepec', 'San Dionisio Ocotepec'),
	('San Dionisio Ocotlán', 'San Dionisio Ocotlán'),
	('San Esteban Atatlahuca', 'San Esteban Atatlahuca'),
	('San Felipe Jalapa de Díaz', 'San Felipe Jalapa de Díaz'),
	('San Felipe Tejalápam', 'San Felipe Tejalápam'),
	('San Felipe Usila', 'San Felipe Usila'),
	('San Francisco Cahuacuá', 'San Francisco Cahuacuá'),
	('San Francisco Cajonos', 'San Francisco Cajonos'),
	('San Francisco Chapulapa', 'San Francisco Chapulapa'),
	('San Francisco Chindúa', 'San Francisco Chindúa'),
	('San Francisco del Mar', 'San Francisco del Mar'),
	('San Francisco Huehuetlán', 'San Francisco Huehuetlán'),
	('San Francisco Ixhuatán', 'San Francisco Ixhuatán'),
	('San Francisco Jaltepetongo', 'San Francisco Jaltepetongo'),
	('San Francisco Lachigoló', 'San Francisco Lachigoló'),
	('San Francisco Logueche', 'San Francisco Logueche'),
	('San Francisco Nuxaño', 'San Francisco Nuxaño'),
	('San Francisco Ozolotepec', 'San Francisco Ozolotepec'),
	('San Francisco Sola', 'San Francisco Sola'),
	('San Francisco Telixtlahuaca', 'San Francisco Telixtlahuaca'),
	('San Francisco Teopan', 'San Francisco Teopan'),
	('San Francisco Tlapancingo', 'San Francisco Tlapancingo'),
	('San Gabriel Mixtepec', 'San Gabriel Mixtepec'),
	('San Ildefonso Amatlán', 'San Ildefonso Amatlán'),
	('San Ildefonso Sola', 'San Ildefonso Sola'),
	('San Ildefonso Villa Alta', 'San Ildefonso Villa Alta'),
	('San Jacinto Amilpas', 'San Jacinto Amilpas'),
	('San Jacinto Tlacotepec', 'San Jacinto Tlacotepec'),
	('San Jerónimo Coatlán', 'San Jerónimo Coatlán'),
	('San Jerónimo Silacayoapilla', 'San Jerónimo Silacayoapilla'),
	('San Jerónimo Sosola', 'San Jerónimo Sosola'),
	('San Jerónimo Taviche', 'San Jerónimo Taviche'),
	('San Jerónimo Tecóatl', 'San Jerónimo Tecóatl'),
	('San Jorge Nuchita', 'San Jorge Nuchita'),
	('San José Ayuquila', 'San José Ayuquila'),
	('San José Chiltepec', 'San José Chiltepec'),
	('San José del Peñasco', 'San José del Peñasco'),
	('San José Estancia Grande', 'San José Estancia Grande'),
	('San José Independencia', 'San José Independencia'),
	('San José Lachiguiri', 'San José Lachiguiri'),
	('San José Tenango', 'San José Tenango'),
	('San Juan Achiutla', 'San Juan Achiutla'),
	('San Juan Atepec', 'San Juan Atepec'),
	('Ánimas Trujano', 'Ánimas Trujano'),
	('San Juan Bautista Atatlahuca', 'San Juan Bautista Atatlahuca'),
	('San Juan Bautista Coixtlahuaca', 'San Juan Bautista Coixtlahuaca'),
	('San Juan Bautista Cuicatlán', 'San Juan Bautista Cuicatlán'),
	('San Juan Bautista Guelache', 'San Juan Bautista Guelache'),
	('San Juan Bautista Jayacatlán', 'San Juan Bautista Jayacatlán'),
	('San Juan Bautista Lo de Soto', 'San Juan Bautista Lo de Soto'),
	('San Juan Bautista Suchitepec', 'San Juan Bautista Suchitepec'),
	('San Juan Bautista Tlacoatzintepec', 'San Juan Bautista Tlacoatzintepec'),
	('San Juan Bautista Tlachichilco', 'San Juan Bautista Tlachichilco'),
	('San Juan Bautista Tuxtepec', 'San Juan Bautista Tuxtepec'),
	('San Juan Cacahuatepec', 'San Juan Cacahuatepec'),
	('San Juan Cieneguilla', 'San Juan Cieneguilla'),
	('San Juan Coatzóspam', 'San Juan Coatzóspam'),
	('San Juan Colorado', 'San Juan Colorado'),
	('San Juan Comaltepec', 'San Juan Comaltepec'),
	('San Juan Cotzocón', 'San Juan Cotzocón'),
	('San Juan Chicomezúchil', 'San Juan Chicomezúchil'),
	('San Juan Chilateca', 'San Juan Chilateca'),
	('San Juan del Estado', 'San Juan del Estado'),
	('San Juan del Río', 'San Juan del Río'),
	('San Juan Diuxi', 'San Juan Diuxi'),
	('San Juan Evangelista Analco', 'San Juan Evangelista Analco'),
	('San Juan Guelavía', 'San Juan Guelavía'),
	('San Juan Guichicovi', 'San Juan Guichicovi'),
	('San Juan Ihualtepec', 'San Juan Ihualtepec'),
	('San Juan Juquila Mixes', 'San Juan Juquila Mixes'),
	('San Juan Juquila Vijanos', 'San Juan Juquila Vijanos'),
	('San Juan Lachao', 'San Juan Lachao'),
	('San Juan Lachigalla', 'San Juan Lachigalla'),
	('San Juan Lajarcia', 'San Juan Lajarcia'),
	('San Juan Lalana', 'San Juan Lalana'),
	('San Juan de los Cués', 'San Juan de los Cués'),
	('San Juan Mazatlán', 'San Juan Mazatlán'),
	('San Juan Mixtepec -Dto. 08 -', 'San Juan Mixtepec -Dto. 08 -'),
	('San Juan Mixtepec -Dto. 26 -', 'San Juan Mixtepec -Dto. 26 -'),
	('San Juan Ñumí', 'San Juan Ñumí'),
	('San Juan Ozolotepec', 'San Juan Ozolotepec'),
	('San Juan Petlapa', 'San Juan Petlapa'),
	('San Juan Quiahije', 'San Juan Quiahije'),
	('San Juan Quiotepec', 'San Juan Quiotepec'),
	('San Juan Sayultepec', 'San Juan Sayultepec'),
	('San Juan Tabaá', 'San Juan Tabaá'),
	('San Juan Tamazola', 'San Juan Tamazola'),
	('San Juan Teita', 'San Juan Teita'),
	('San Juan Teitipac', 'San Juan Teitipac'),
	('San Juan Tepeuxila', 'San Juan Tepeuxila'),
	('San Juan Teposcolula', 'San Juan Teposcolula'),
	('San Juan Yaeé', 'San Juan Yaeé'),
	('San Juan Yatzona', 'San Juan Yatzona'),
	('San Juan Yucuita', 'San Juan Yucuita'),
	('San Lorenzo', 'San Lorenzo'),
	('San Lorenzo Albarradas', 'San Lorenzo Albarradas'),
	('San Lorenzo Cacaotepec', 'San Lorenzo Cacaotepec'),
	('San Lorenzo Cuaunecuiltitla', 'San Lorenzo Cuaunecuiltitla'),
	('San Lorenzo Texmelúcan', 'San Lorenzo Texmelúcan'),
	('San Lorenzo Victoria', 'San Lorenzo Victoria'),
	('San Lucas Camotlán', 'San Lucas Camotlán'),
	('San Lucas Ojitlán', 'San Lucas Ojitlán'),
	('San Lucas Quiaviní', 'San Lucas Quiaviní'),
	('San Lucas Zoquiápam', 'San Lucas Zoquiápam'),
	('San Luis Amatlán', 'San Luis Amatlán'),
	('San Marcial Ozolotepec', 'San Marcial Ozolotepec'),
	('San Marcos Arteaga', 'San Marcos Arteaga'),
	('San Martín de los Cansecos', 'San Martín de los Cansecos'),
	('San Martín Huamelúlpam', 'San Martín Huamelúlpam'),
	('San Martín Itunyoso', 'San Martín Itunyoso'),
	('San Martín Lachilá', 'San Martín Lachilá'),
	('San Martín Peras', 'San Martín Peras'),
	('San Martín Tilcajete', 'San Martín Tilcajete'),
	('San Martín Toxpalan', 'San Martín Toxpalan'),
	('San Martín Zacatepec', 'San Martín Zacatepec'),
	('San Mateo Cajonos', 'San Mateo Cajonos'),
	('Capulálpam de Méndez', 'Capulálpam de Méndez'),
	('San Mateo del Mar', 'San Mateo del Mar'),
	('San Mateo Yoloxochitlán', 'San Mateo Yoloxochitlán'),
	('San Mateo Etlatongo', 'San Mateo Etlatongo'),
	('San Mateo Nejápam', 'San Mateo Nejápam'),
	('San Mateo Peñasco', 'San Mateo Peñasco'),
	('San Mateo Piñas', 'San Mateo Piñas'),
	('San Mateo Río Hondo', 'San Mateo Río Hondo'),
	('San Mateo Sindihui', 'San Mateo Sindihui'),
	('San Mateo Tlapiltepec', 'San Mateo Tlapiltepec'),
	('San Melchor Betaza', 'San Melchor Betaza'),
	('San Miguel Achiutla', 'San Miguel Achiutla'),
	('San Miguel Ahuehuetitlán', 'San Miguel Ahuehuetitlán'),
	('San Miguel Aloápam', 'San Miguel Aloápam'),
	('San Miguel Amatitlán', 'San Miguel Amatitlán'),
	('San Miguel Amatlán', 'San Miguel Amatlán'),
	('San Miguel Coatlán', 'San Miguel Coatlán'),
	('San Miguel Chicahua', 'San Miguel Chicahua'),
	('San Miguel Chimalapa', 'San Miguel Chimalapa'),
	('San Miguel del Puerto', 'San Miguel del Puerto'),
	('San Miguel del Río', 'San Miguel del Río'),
	('San Miguel Ejutla', 'San Miguel Ejutla'),
	('San Miguel el Grande', 'San Miguel el Grande'),
	('San Miguel Huautla', 'San Miguel Huautla'),
	('San Miguel Mixtepec', 'San Miguel Mixtepec'),
	('San Miguel Panixtlahuaca', 'San Miguel Panixtlahuaca'),
	('San Miguel Peras', 'San Miguel Peras'),
	('San Miguel Piedras', 'San Miguel Piedras'),
	('San Miguel Quetzaltepec', 'San Miguel Quetzaltepec'),
	('San Miguel Santa Flor', 'San Miguel Santa Flor'),
	('Villa Sola de Vega', 'Villa Sola de Vega'),
	('San Miguel Soyaltepec', 'San Miguel Soyaltepec'),
	('San Miguel Suchixtepec', 'San Miguel Suchixtepec'),
	('Villa Talea de Castro', 'Villa Talea de Castro'),
	('San Miguel Tecomatlán', 'San Miguel Tecomatlán'),
	('San Miguel Tenango', 'San Miguel Tenango'),
	('San Miguel Tequixtepec', 'San Miguel Tequixtepec'),
	('San Miguel Tilquiápam', 'San Miguel Tilquiápam'),
	('San Miguel Tlacamama', 'San Miguel Tlacamama'),
	('San Miguel Tlacotepec', 'San Miguel Tlacotepec'),
	('San Miguel Tulancingo', 'San Miguel Tulancingo'),
	('San Miguel Yotao', 'San Miguel Yotao'),
	('San Nicolás', 'San Nicolás'),
	('San Nicolás Hidalgo', 'San Nicolás Hidalgo'),
	('San Pablo Coatlán', 'San Pablo Coatlán'),
	('San Pablo Cuatro Venados', 'San Pablo Cuatro Venados'),
	('San Pablo Etla', 'San Pablo Etla'),
	('San Pablo Huitzo', 'San Pablo Huitzo'),
	('San Pablo Huixtepec', 'San Pablo Huixtepec'),
	('San Pablo Macuiltianguis', 'San Pablo Macuiltianguis'),
	('San Pablo Tijaltepec', 'San Pablo Tijaltepec'),
	('San Pablo Villa de Mitla', 'San Pablo Villa de Mitla'),
	('San Pablo Yaganiza', 'San Pablo Yaganiza'),
	('San Pedro Amuzgos', 'San Pedro Amuzgos'),
	('San Pedro Apóstol', 'San Pedro Apóstol'),
	('San Pedro Atoyac', 'San Pedro Atoyac'),
	('San Pedro Cajonos', 'San Pedro Cajonos'),
	('San Pedro Coxcaltepec Cántaros', 'San Pedro Coxcaltepec Cántaros'),
	('San Pedro Comitancillo', 'San Pedro Comitancillo'),
	('San Pedro el Alto', 'San Pedro el Alto'),
	('San Pedro Huamelula', 'San Pedro Huamelula'),
	('San Pedro Huilotepec', 'San Pedro Huilotepec'),
	('San Pedro Ixcatlán', 'San Pedro Ixcatlán'),
	('San Pedro Ixtlahuaca', 'San Pedro Ixtlahuaca'),
	('San Pedro Jaltepetongo', 'San Pedro Jaltepetongo'),
	('San Pedro Jicayán', 'San Pedro Jicayán'),
	('San Pedro Jocotipac', 'San Pedro Jocotipac'),
	('San Pedro Juchatengo', 'San Pedro Juchatengo'),
	('San Pedro Mártir', 'San Pedro Mártir'),
	('San Pedro Mártir Quiechapa', 'San Pedro Mártir Quiechapa'),
	('San Pedro Mártir Yucuxaco', 'San Pedro Mártir Yucuxaco'),
	('San Pedro Mixtepec -Dto. 22 -', 'San Pedro Mixtepec -Dto. 22 -'),
	('San Pedro Mixtepec -Dto. 26 -', 'San Pedro Mixtepec -Dto. 26 -'),
	('San Pedro Molinos', 'San Pedro Molinos'),
	('San Pedro Nopala', 'San Pedro Nopala'),
	('San Pedro Ocopetatillo', 'San Pedro Ocopetatillo'),
	('San Pedro Ocotepec', 'San Pedro Ocotepec'),
	('San Pedro Pochutla', 'San Pedro Pochutla'),
	('San Pedro Quiatoni', 'San Pedro Quiatoni'),
	('San Pedro Sochiápam', 'San Pedro Sochiápam'),
	('San Pedro Tapanatepec', 'San Pedro Tapanatepec'),
	('San Pedro Taviche', 'San Pedro Taviche'),
	('San Pedro Teozacoalco', 'San Pedro Teozacoalco'),
	('San Pedro Teutila', 'San Pedro Teutila'),
	('San Pedro Tidaá', 'San Pedro Tidaá'),
	('San Pedro Topiltepec', 'San Pedro Topiltepec'),
	('San Pedro Totolápam', 'San Pedro Totolápam'),
	('Villa de Tututepec de Melchor Ocampo', 'Villa de Tututepec de Melchor Ocampo'),
	('San Pedro Yaneri', 'San Pedro Yaneri'),
	('San Pedro Yólox', 'San Pedro Yólox'),
	('San Pedro y San Pablo Ayutla', 'San Pedro y San Pablo Ayutla'),
	('Villa de Etla', 'Villa de Etla'),
	('San Pedro y San Pablo Teposcolula', 'San Pedro y San Pablo Teposcolula'),
	('San Pedro y San Pablo Tequixtepec', 'San Pedro y San Pablo Tequixtepec'),
	('San Pedro Yucunama', 'San Pedro Yucunama'),
	('San Raymundo Jalpan', 'San Raymundo Jalpan'),
	('San Sebastián Abasolo', 'San Sebastián Abasolo'),
	('San Sebastián Coatlán', 'San Sebastián Coatlán'),
	('San Sebastián Ixcapa', 'San Sebastián Ixcapa'),
	('San Sebastián Nicananduta', 'San Sebastián Nicananduta'),
	('San Sebastián Río Hondo', 'San Sebastián Río Hondo'),
	('San Sebastián Tecomaxtlahuaca', 'San Sebastián Tecomaxtlahuaca'),
	('San Sebastián Teitipac', 'San Sebastián Teitipac'),
	('San Sebastián Tutla', 'San Sebastián Tutla'),
	('San Simón Almolongas', 'San Simón Almolongas'),
	('San Simón Zahuatlán', 'San Simón Zahuatlán'),
	('Santa Ana', 'Santa Ana'),
	('Santa Ana Ateixtlahuaca', 'Santa Ana Ateixtlahuaca'),
	('Santa Ana Cuauhtémoc', 'Santa Ana Cuauhtémoc'),
	('Santa Ana del Valle', 'Santa Ana del Valle'),
	('Santa Ana Tavela', 'Santa Ana Tavela'),
	('Santa Ana Tlapacoyan', 'Santa Ana Tlapacoyan'),
	('Santa Ana Yareni', 'Santa Ana Yareni'),
	('Santa Ana Zegache', 'Santa Ana Zegache'),
	('Santa Catalina Quierí', 'Santa Catalina Quierí'),
	('Santa Catarina Cuixtla', 'Santa Catarina Cuixtla'),
	('Santa Catarina Ixtepeji', 'Santa Catarina Ixtepeji'),
	('Santa Catarina Juquila', 'Santa Catarina Juquila'),
	('Santa Catarina Lachatao', 'Santa Catarina Lachatao'),
	('Santa Catarina Loxicha', 'Santa Catarina Loxicha'),
	('Santa Catarina Mechoacán', 'Santa Catarina Mechoacán'),
	('Santa Catarina Minas', 'Santa Catarina Minas'),
	('Santa Catarina Quiané', 'Santa Catarina Quiané'),
	('Santa Catarina Tayata', 'Santa Catarina Tayata'),
	('Santa Catarina Ticuá', 'Santa Catarina Ticuá'),
	('Santa Catarina Yosonotú', 'Santa Catarina Yosonotú'),
	('Santa Catarina Zapoquila', 'Santa Catarina Zapoquila'),
	('Santa Cruz Acatepec', 'Santa Cruz Acatepec'),
	('Santa Cruz Amilpas', 'Santa Cruz Amilpas'),
	('Santa Cruz de Bravo', 'Santa Cruz de Bravo'),
	('Santa Cruz Itundujia', 'Santa Cruz Itundujia'),
	('Santa Cruz Mixtepec', 'Santa Cruz Mixtepec'),
	('Santa Cruz Nundaco', 'Santa Cruz Nundaco'),
	('Santa Cruz Papalutla', 'Santa Cruz Papalutla'),
	('Santa Cruz Tacache de Mina', 'Santa Cruz Tacache de Mina'),
	('Santa Cruz Tacahua', 'Santa Cruz Tacahua'),
	('Santa Cruz Tayata', 'Santa Cruz Tayata'),
	('Santa Cruz Xitla', 'Santa Cruz Xitla'),
	('Santa Cruz Xoxocotlán', 'Santa Cruz Xoxocotlán'),
	('Santa Cruz Zenzontepec', 'Santa Cruz Zenzontepec'),
	('Santa Gertrudis', 'Santa Gertrudis'),
	('Santa Inés del Monte', 'Santa Inés del Monte'),
	('Santa Inés Yatzeche', 'Santa Inés Yatzeche'),
	('Santa Lucía del Camino', 'Santa Lucía del Camino'),
	('Santa Lucía Miahuatlán', 'Santa Lucía Miahuatlán'),
	('Santa Lucía Monteverde', 'Santa Lucía Monteverde'),
	('Santa Lucía Ocotlán', 'Santa Lucía Ocotlán'),
	('Santa María Alotepec', 'Santa María Alotepec'),
	('Santa María Apazco', 'Santa María Apazco'),
	('Santa María la Asunción', 'Santa María la Asunción'),
	('Heroica Ciudad de Tlaxiaco', 'Heroica Ciudad de Tlaxiaco'),
	('Ayoquezco de Aldama', 'Ayoquezco de Aldama'),
	('Santa María Atzompa', 'Santa María Atzompa'),
	('Santa María Camotlán', 'Santa María Camotlán'),
	('Santa María Colotepec', 'Santa María Colotepec'),
	('Santa María Cortijo', 'Santa María Cortijo'),
	('Santa María Coyotepec', 'Santa María Coyotepec'),
	('Santa María Chachoápam', 'Santa María Chachoápam'),
	('Villa de Chilapa de Díaz', 'Villa de Chilapa de Díaz'),
	('Santa María Chilchotla', 'Santa María Chilchotla'),
	('Santa María Chimalapa', 'Santa María Chimalapa'),
	('Santa María del Rosario', 'Santa María del Rosario'),
	('Santa María del Tule', 'Santa María del Tule'),
	('Santa María Ecatepec', 'Santa María Ecatepec'),
	('Santa María Guelacé', 'Santa María Guelacé'),
	('Santa María Guienagati', 'Santa María Guienagati'),
	('Santa María Huatulco', 'Santa María Huatulco'),
	('Santa María Huazolotitlán', 'Santa María Huazolotitlán'),
	('Santa María Ipalapa', 'Santa María Ipalapa'),
	('Santa María Ixcatlán', 'Santa María Ixcatlán'),
	('Santa María Jacatepec', 'Santa María Jacatepec'),
	('Santa María Jalapa del Marqués', 'Santa María Jalapa del Marqués'),
	('Santa María Jaltianguis', 'Santa María Jaltianguis'),
	('Santa María Lachixío', 'Santa María Lachixío'),
	('Santa María Mixtequilla', 'Santa María Mixtequilla'),
	('Santa María Nativitas', 'Santa María Nativitas'),
	('Santa María Nduayaco', 'Santa María Nduayaco'),
	('Santa María Ozolotepec', 'Santa María Ozolotepec'),
	('Santa María Pápalo', 'Santa María Pápalo'),
	('Santa María Peñoles', 'Santa María Peñoles'),
	('Santa María Petapa', 'Santa María Petapa'),
	('Santa María Quiegolani', 'Santa María Quiegolani'),
	('Santa María Sola', 'Santa María Sola'),
	('Santa María Tataltepec', 'Santa María Tataltepec'),
	('Santa María Tecomavaca', 'Santa María Tecomavaca'),
	('Santa María Temaxcalapa', 'Santa María Temaxcalapa'),
	('Santa María Temaxcaltepec', 'Santa María Temaxcaltepec'),
	('Santa María Teopoxco', 'Santa María Teopoxco'),
	('Santa María Tepantlali', 'Santa María Tepantlali'),
	('Santa María Texcatitlán', 'Santa María Texcatitlán'),
	('Santa María Tlahuitoltepec', 'Santa María Tlahuitoltepec'),
	('Santa María Tlalixtac', 'Santa María Tlalixtac'),
	('Santa María Tonameca', 'Santa María Tonameca'),
	('Santa María Totolapilla', 'Santa María Totolapilla'),
	('Santa María Xadani', 'Santa María Xadani'),
	('Santa María Yalina', 'Santa María Yalina'),
	('Santa María Yavesía', 'Santa María Yavesía'),
	('Santa María Yolotepec', 'Santa María Yolotepec'),
	('Santa María Yosoyúa', 'Santa María Yosoyúa'),
	('Santa María Yucuhiti', 'Santa María Yucuhiti'),
	('Santa María Zacatepec', 'Santa María Zacatepec'),
	('Santa María Zaniza', 'Santa María Zaniza'),
	('Santa María Zoquitlán', 'Santa María Zoquitlán'),
	('Santiago Amoltepec', 'Santiago Amoltepec'),
	('Santiago Apoala', 'Santiago Apoala'),
	('Santiago Apóstol', 'Santiago Apóstol'),
	('Santiago Astata', 'Santiago Astata'),
	('Santiago Atitlán', 'Santiago Atitlán'),
	('Santiago Ayuquililla', 'Santiago Ayuquililla'),
	('Santiago Cacaloxtepec', 'Santiago Cacaloxtepec'),
	('Santiago Camotlán', 'Santiago Camotlán'),
	('Santiago Comaltepec', 'Santiago Comaltepec'),
	('Santiago Chazumba', 'Santiago Chazumba'),
	('Santiago Choápam', 'Santiago Choápam'),
	('Santiago del Río', 'Santiago del Río'),
	('Santiago Huajolotitlán', 'Santiago Huajolotitlán'),
	('Santiago Huauclilla', 'Santiago Huauclilla'),
	('Santiago Ihuitlán Plumas', 'Santiago Ihuitlán Plumas'),
	('Santiago Ixcuintepec', 'Santiago Ixcuintepec'),
	('Santiago Ixtayutla', 'Santiago Ixtayutla'),
	('Santiago Jamiltepec', 'Santiago Jamiltepec'),
	('Santiago Jocotepec', 'Santiago Jocotepec'),
	('Santiago Juxtlahuaca', 'Santiago Juxtlahuaca'),
	('Santiago Lachiguiri', 'Santiago Lachiguiri'),
	('Santiago Lalopa', 'Santiago Lalopa'),
	('Santiago Laollaga', 'Santiago Laollaga'),
	('Santiago Laxopa', 'Santiago Laxopa'),
	('Santiago Llano Grande', 'Santiago Llano Grande'),
	('Santiago Matatlán', 'Santiago Matatlán'),
	('Santiago Miltepec', 'Santiago Miltepec'),
	('Santiago Minas', 'Santiago Minas'),
	('Santiago Nacaltepec', 'Santiago Nacaltepec'),
	('Santiago Nejapilla', 'Santiago Nejapilla'),
	('Santiago Nundiche', 'Santiago Nundiche'),
	('Santiago Nuyoó', 'Santiago Nuyoó'),
	('Santiago Pinotepa Nacional', 'Santiago Pinotepa Nacional'),
	('Santiago Suchilquitongo', 'Santiago Suchilquitongo'),
	('Santiago Tamazola', 'Santiago Tamazola'),
	('Santiago Tapextla', 'Santiago Tapextla'),
	('Villa Tejúpam de la Unión', 'Villa Tejúpam de la Unión'),
	('Santiago Tenango', 'Santiago Tenango'),
	('Santiago Tepetlapa', 'Santiago Tepetlapa'),
	('Santiago Tetepec', 'Santiago Tetepec'),
	('Santiago Texcalcingo', 'Santiago Texcalcingo'),
	('Santiago Textitlán', 'Santiago Textitlán'),
	('Santiago Tilantongo', 'Santiago Tilantongo'),
	('Santiago Tillo', 'Santiago Tillo'),
	('Santiago Tlazoyaltepec', 'Santiago Tlazoyaltepec'),
	('Santiago Xanica', 'Santiago Xanica'),
	('Santiago Xiacuí', 'Santiago Xiacuí'),
	('Santiago Yaitepec', 'Santiago Yaitepec'),
	('Santiago Yaveo', 'Santiago Yaveo'),
	('Santiago Yolomécatl', 'Santiago Yolomécatl'),
	('Santiago Yosondúa', 'Santiago Yosondúa'),
	('Santiago Yucuyachi', 'Santiago Yucuyachi'),
	('Santiago Zacatepec', 'Santiago Zacatepec'),
	('Santiago Zoochila', 'Santiago Zoochila'),
	('Nuevo Zoquiápam', 'Nuevo Zoquiápam'),
	('Santo Domingo Ingenio', 'Santo Domingo Ingenio'),
	('Santo Domingo Albarradas', 'Santo Domingo Albarradas'),
	('Santo Domingo Armenta', 'Santo Domingo Armenta'),
	('Santo Domingo Chihuitán', 'Santo Domingo Chihuitán'),
	('Santo Domingo de Morelos', 'Santo Domingo de Morelos'),
	('Santo Domingo Ixcatlán', 'Santo Domingo Ixcatlán'),
	('Santo Domingo Nuxaá', 'Santo Domingo Nuxaá'),
	('Santo Domingo Ozolotepec', 'Santo Domingo Ozolotepec'),
	('Santo Domingo Petapa', 'Santo Domingo Petapa'),
	('Santo Domingo Roayaga', 'Santo Domingo Roayaga'),
	('Santo Domingo Tehuantepec', 'Santo Domingo Tehuantepec'),
	('Santo Domingo Teojomulco', 'Santo Domingo Teojomulco'),
	('Santo Domingo Tepuxtepec', 'Santo Domingo Tepuxtepec'),
	('Santo Domingo Tlatayápam', 'Santo Domingo Tlatayápam'),
	('Santo Domingo Tomaltepec', 'Santo Domingo Tomaltepec'),
	('Santo Domingo Tonalá', 'Santo Domingo Tonalá'),
	('Santo Domingo Tonaltepec', 'Santo Domingo Tonaltepec'),
	('Santo Domingo Xagacía', 'Santo Domingo Xagacía'),
	('Santo Domingo Yanhuitlán', 'Santo Domingo Yanhuitlán'),
	('Santo Domingo Yodohino', 'Santo Domingo Yodohino'),
	('Santo Domingo Zanatepec', 'Santo Domingo Zanatepec'),
	('Santos Reyes Nopala', 'Santos Reyes Nopala'),
	('Santos Reyes Pápalo', 'Santos Reyes Pápalo'),
	('Santos Reyes Tepejillo', 'Santos Reyes Tepejillo'),
	('Santos Reyes Yucuná', 'Santos Reyes Yucuná'),
	('Santo Tomás Jalieza', 'Santo Tomás Jalieza'),
	('Santo Tomás Mazaltepec', 'Santo Tomás Mazaltepec'),
	('Santo Tomás Ocotepec', 'Santo Tomás Ocotepec'),
	('Santo Tomás Tamazulapan', 'Santo Tomás Tamazulapan'),
	('San Vicente Coatlán', 'San Vicente Coatlán'),
	('San Vicente Lachixío', 'San Vicente Lachixío'),
	('San Vicente Nuñú', 'San Vicente Nuñú'),
	('Silacayoápam', 'Silacayoápam'),
	('Sitio de Xitlapehua', 'Sitio de Xitlapehua'),
	('Soledad Etla', 'Soledad Etla'),
	('Villa de Tamazulápam del Progreso', 'Villa de Tamazulápam del Progreso'),
	('Tanetze de Zaragoza', 'Tanetze de Zaragoza'),
	('Taniche', 'Taniche'),
	('Tataltepec de Valdés', 'Tataltepec de Valdés'),
	('Teococuilco de Marcos Pérez', 'Teococuilco de Marcos Pérez'),
	('Teotitlán de Flores Magón', 'Teotitlán de Flores Magón'),
	('Teotitlán del Valle', 'Teotitlán del Valle'),
	('Teotongo', 'Teotongo'),
	('Tepelmeme Villa de Morelos', 'Tepelmeme Villa de Morelos'),
	('Heroica Villa Tezoatlán de Segura y Luna, Cuna de la Independencia de Oaxaca', 'Heroica Villa Tezoatlán de Segura y Luna, Cuna de la Independencia de Oaxaca'),
	('San Jerónimo Tlacochahuaya', 'San Jerónimo Tlacochahuaya'),
	('Tlacolula de Matamoros', 'Tlacolula de Matamoros'),
	('Tlacotepec Plumas', 'Tlacotepec Plumas'),
	('Tlalixtac de Cabrera', 'Tlalixtac de Cabrera'),
	('Totontepec Villa de Morelos', 'Totontepec Villa de Morelos'),
	('Trinidad Zaachila', 'Trinidad Zaachila'),
	('La Trinidad Vista Hermosa', 'La Trinidad Vista Hermosa'),
	('Unión Hidalgo', 'Unión Hidalgo'),
	('Valerio Trujano', 'Valerio Trujano'),
	('San Juan Bautista Valle Nacional', 'San Juan Bautista Valle Nacional'),
	('Villa Díaz Ordaz', 'Villa Díaz Ordaz'),
	('Yaxe', 'Yaxe'),
	('Magdalena Yodocono de Porfirio Díaz', 'Magdalena Yodocono de Porfirio Díaz'),
	('Yogana', 'Yogana'),
	('Yutanduchi de Guerrero', 'Yutanduchi de Guerrero'),
	('Villa de Zaachila', 'Villa de Zaachila'),
	('San Mateo Yucutindó', 'San Mateo Yucutindó'),
	('Zapotitlán Lagunas', 'Zapotitlán Lagunas'),
	('Zapotitlán Palmas', 'Zapotitlán Palmas'),
	('Santa Inés de Zaragoza', 'Santa Inés de Zaragoza'),
	('Zimatlán de Álvarez', 'Zimatlán de Álvarez'),
	('Acajete', 'Acajete'),
	('Acateno', 'Acateno'),
	('Acatlán', 'Acatlán'),
	('Acatzingo', 'Acatzingo'),
	('Acteopan', 'Acteopan'),
	('Ahuacatlán', 'Ahuacatlán'),
	('Ahuatlán', 'Ahuatlán'),
	('Ahuazotepec', 'Ahuazotepec'),
	('Ahuehuetitla', 'Ahuehuetitla'),
	('Ajalpan', 'Ajalpan'),
	('Albino Zertuche', 'Albino Zertuche'),
	('Aljojuca', 'Aljojuca'),
	('Altepexi', 'Altepexi'),
	('Amixtlán', 'Amixtlán'),
	('Amozoc', 'Amozoc'),
	('Aquixtla', 'Aquixtla'),
	('Atempan', 'Atempan'),
	('Atexcal', 'Atexcal'),
	('Atlixco', 'Atlixco'),
	('Atoyatempan', 'Atoyatempan'),
	('Atzala', 'Atzala'),
	('Atzitzihuacán', 'Atzitzihuacán'),
	('Atzitzintla', 'Atzitzintla'),
	('Axutla', 'Axutla'),
	('Ayotoxco de Guerrero', 'Ayotoxco de Guerrero'),
	('Calpan', 'Calpan'),
	('Caltepec', 'Caltepec'),
	('Camocuautla', 'Camocuautla'),
	('Caxhuacan', 'Caxhuacan'),
	('Coatepec', 'Coatepec'),
	('Coatzingo', 'Coatzingo'),
	('Cohetzala', 'Cohetzala'),
	('Cohuecan', 'Cohuecan'),
	('Coronango', 'Coronango'),
	('Coxcatlán', 'Coxcatlán'),
	('Coyomeapan', 'Coyomeapan'),
	('Coyotepec', 'Coyotepec'),
	('Cuapiaxtla de Madero', 'Cuapiaxtla de Madero'),
	('Cuautempan', 'Cuautempan'),
	('Cuautinchán', 'Cuautinchán'),
	('Cuautlancingo', 'Cuautlancingo'),
	('Cuayuca de Andrade', 'Cuayuca de Andrade'),
	('Cuetzalan del Progreso', 'Cuetzalan del Progreso'),
	('Cuyoaco', 'Cuyoaco'),
	('Chalchicomula de Sesma', 'Chalchicomula de Sesma'),
	('Chapulco', 'Chapulco'),
	('Chiautla', 'Chiautla'),
	('Chiautzingo', 'Chiautzingo'),
	('Chiconcuautla', 'Chiconcuautla'),
	('Chichiquila', 'Chichiquila'),
	('Chietla', 'Chietla'),
	('Chigmecatitlán', 'Chigmecatitlán'),
	('Chignahuapan', 'Chignahuapan'),
	('Chignautla', 'Chignautla'),
	('Chila', 'Chila'),
	('Chila de la Sal', 'Chila de la Sal'),
	('Honey', 'Honey'),
	('Chilchotla', 'Chilchotla'),
	('Chinantla', 'Chinantla'),
	('Domingo Arenas', 'Domingo Arenas'),
	('Eloxochitlán', 'Eloxochitlán'),
	('Epatlán', 'Epatlán'),
	('Esperanza', 'Esperanza'),
	('Francisco Z. Mena', 'Francisco Z. Mena'),
	('General Felipe Ángeles', 'General Felipe Ángeles'),
	('Guadalupe', 'Guadalupe'),
	('Guadalupe Victoria', 'Guadalupe Victoria'),
	('Hermenegildo Galeana', 'Hermenegildo Galeana'),
	('Huaquechula', 'Huaquechula'),
	('Huatlatlauca', 'Huatlatlauca'),
	('Huauchinango', 'Huauchinango'),
	('Huehuetla', 'Huehuetla'),
	('Huehuetlán el Chico', 'Huehuetlán el Chico'),
	('Huejotzingo', 'Huejotzingo'),
	('Hueyapan', 'Hueyapan'),
	('Hueytamalco', 'Hueytamalco'),
	('Hueytlalpan', 'Hueytlalpan'),
	('Huitzilan de Serdán', 'Huitzilan de Serdán'),
	('Huitziltepec', 'Huitziltepec'),
	('Atlequizayan', 'Atlequizayan'),
	('Ixcamilpa de Guerrero', 'Ixcamilpa de Guerrero'),
	('Ixcaquixtla', 'Ixcaquixtla'),
	('Ixtacamaxtitlán', 'Ixtacamaxtitlán'),
	('Ixtepec', 'Ixtepec'),
	('Izúcar de Matamoros', 'Izúcar de Matamoros'),
	('Jalpan', 'Jalpan'),
	('Jolalpan', 'Jolalpan'),
	('Jonotla', 'Jonotla'),
	('Jopala', 'Jopala'),
	('Juan C. Bonilla', 'Juan C. Bonilla'),
	('Juan Galindo', 'Juan Galindo'),
	('Juan N. Méndez', 'Juan N. Méndez'),
	('Lafragua', 'Lafragua'),
	('Libres', 'Libres'),
	('La Magdalena Tlatlauquitepec', 'La Magdalena Tlatlauquitepec'),
	('Mazapiltepec de Juárez', 'Mazapiltepec de Juárez'),
	('Mixtla', 'Mixtla'),
	('Molcaxac', 'Molcaxac'),
	('Cañada Morelos', 'Cañada Morelos'),
	('Naupan', 'Naupan'),
	('Nauzontla', 'Nauzontla'),
	('Nealtican', 'Nealtican'),
	('Nicolás Bravo', 'Nicolás Bravo'),
	('Nopalucan', 'Nopalucan'),
	('Ocotepec', 'Ocotepec'),
	('Ocoyucan', 'Ocoyucan'),
	('Olintla', 'Olintla'),
	('Oriental', 'Oriental'),
	('Pahuatlán', 'Pahuatlán'),
	('Palmar de Bravo', 'Palmar de Bravo'),
	('Pantepec', 'Pantepec'),
	('Petlalcingo', 'Petlalcingo'),
	('Piaxtla', 'Piaxtla'),
	('Puebla', 'Puebla'),
	('Quecholac', 'Quecholac'),
	('Quimixtlán', 'Quimixtlán'),
	('Rafael Lara Grajales', 'Rafael Lara Grajales'),
	('Los Reyes de Juárez', 'Los Reyes de Juárez'),
	('San Andrés Cholula', 'San Andrés Cholula'),
	('San Antonio Cañada', 'San Antonio Cañada'),
	('San Diego la Mesa Tochimiltzingo', 'San Diego la Mesa Tochimiltzingo'),
	('San Felipe Teotlalcingo', 'San Felipe Teotlalcingo'),
	('San Felipe Tepatlán', 'San Felipe Tepatlán'),
	('San Gabriel Chilac', 'San Gabriel Chilac'),
	('San Gregorio Atzompa', 'San Gregorio Atzompa'),
	('San Jerónimo Tecuanipan', 'San Jerónimo Tecuanipan'),
	('San Jerónimo Xayacatlán', 'San Jerónimo Xayacatlán'),
	('San José Chiapa', 'San José Chiapa'),
	('San José Miahuatlán', 'San José Miahuatlán'),
	('San Juan Atenco', 'San Juan Atenco'),
	('San Juan Atzompa', 'San Juan Atzompa'),
	('San Martín Texmelucan', 'San Martín Texmelucan'),
	('San Martín Totoltepec', 'San Martín Totoltepec'),
	('San Matías Tlalancaleca', 'San Matías Tlalancaleca'),
	('San Miguel Ixitlán', 'San Miguel Ixitlán'),
	('San Miguel Xoxtla', 'San Miguel Xoxtla'),
	('San Nicolás Buenos Aires', 'San Nicolás Buenos Aires'),
	('San Nicolás de los Ranchos', 'San Nicolás de los Ranchos'),
	('San Pablo Anicano', 'San Pablo Anicano'),
	('San Pedro Cholula', 'San Pedro Cholula'),
	('San Pedro Yeloixtlahuaca', 'San Pedro Yeloixtlahuaca'),
	('San Salvador el Seco', 'San Salvador el Seco'),
	('San Salvador el Verde', 'San Salvador el Verde'),
	('San Salvador Huixcolotla', 'San Salvador Huixcolotla'),
	('San Sebastián Tlacotepec', 'San Sebastián Tlacotepec'),
	('Santa Catarina Tlaltempan', 'Santa Catarina Tlaltempan'),
	('Santa Inés Ahuatempan', 'Santa Inés Ahuatempan'),
	('Santa Isabel Cholula', 'Santa Isabel Cholula'),
	('Santiago Miahuatlán', 'Santiago Miahuatlán'),
	('Huehuetlán el Grande', 'Huehuetlán el Grande'),
	('Santo Tomás Hueyotlipan', 'Santo Tomás Hueyotlipan'),
	('Soltepec', 'Soltepec'),
	('Tecali de Herrera', 'Tecali de Herrera'),
	('Tecamachalco', 'Tecamachalco'),
	('Tecomatlán', 'Tecomatlán'),
	('Tehuacán', 'Tehuacán'),
	('Tehuitzingo', 'Tehuitzingo'),
	('Tenampulco', 'Tenampulco'),
	('Teopantlán', 'Teopantlán'),
	('Teotlalco', 'Teotlalco'),
	('Tepanco de López', 'Tepanco de López'),
	('Tepango de Rodríguez', 'Tepango de Rodríguez'),
	('Tepatlaxco de Hidalgo', 'Tepatlaxco de Hidalgo'),
	('Tepeaca', 'Tepeaca'),
	('Tepemaxalco', 'Tepemaxalco'),
	('Tepeojuma', 'Tepeojuma'),
	('Tepetzintla', 'Tepetzintla'),
	('Tepexco', 'Tepexco'),
	('Tepexi de Rodríguez', 'Tepexi de Rodríguez'),
	('Tepeyahualco', 'Tepeyahualco'),
	('Tepeyahualco de Cuauhtémoc', 'Tepeyahualco de Cuauhtémoc'),
	('Tetela de Ocampo', 'Tetela de Ocampo'),
	('Teteles de Avila Castillo', 'Teteles de Avila Castillo'),
	('Teziutlán', 'Teziutlán'),
	('Tianguismanalco', 'Tianguismanalco'),
	('Tilapa', 'Tilapa'),
	('Tlacotepec de Benito Juárez', 'Tlacotepec de Benito Juárez'),
	('Tlacuilotepec', 'Tlacuilotepec'),
	('Tlachichuca', 'Tlachichuca'),
	('Tlahuapan', 'Tlahuapan'),
	('Tlaltenango', 'Tlaltenango'),
	('Tlanepantla', 'Tlanepantla'),
	('Tlaola', 'Tlaola'),
	('Tlapacoya', 'Tlapacoya'),
	('Tlapanalá', 'Tlapanalá'),
	('Tlatlauquitepec', 'Tlatlauquitepec'),
	('Tlaxco', 'Tlaxco'),
	('Tochimilco', 'Tochimilco'),
	('Tochtepec', 'Tochtepec'),
	('Totoltepec de Guerrero', 'Totoltepec de Guerrero'),
	('Tulcingo', 'Tulcingo'),
	('Tuzamapan de Galeana', 'Tuzamapan de Galeana'),
	('Tzicatlacoyan', 'Tzicatlacoyan'),
	('Venustiano Carranza', 'Venustiano Carranza'),
	('Vicente Guerrero', 'Vicente Guerrero'),
	('Xayacatlán de Bravo', 'Xayacatlán de Bravo'),
	('Xicotepec', 'Xicotepec'),
	('Xicotlán', 'Xicotlán'),
	('Xiutetelco', 'Xiutetelco'),
	('Xochiapulco', 'Xochiapulco'),
	('Xochiltepec', 'Xochiltepec'),
	('Xochitlán de Vicente Suárez', 'Xochitlán de Vicente Suárez'),
	('Xochitlán Todos Santos', 'Xochitlán Todos Santos'),
	('Yaonáhuac', 'Yaonáhuac'),
	('Yehualtepec', 'Yehualtepec'),
	('Zacapala', 'Zacapala'),
	('Zacapoaxtla', 'Zacapoaxtla'),
	('Zacatlán', 'Zacatlán'),
	('Zapotitlán', 'Zapotitlán'),
	('Zapotitlán de Méndez', 'Zapotitlán de Méndez'),
	('Zaragoza', 'Zaragoza'),
	('Zautla', 'Zautla'),
	('Zihuateutla', 'Zihuateutla'),
	('Zinacatepec', 'Zinacatepec'),
	('Zongozotla', 'Zongozotla'),
	('Zoquiapan', 'Zoquiapan'),
	('Zoquitlán', 'Zoquitlán'),
	('Amealco de Bonfil', 'Amealco de Bonfil'),
	('Pinal de Amoles', 'Pinal de Amoles'),
	('Arroyo Seco', 'Arroyo Seco'),
	('Cadereyta de Montes', 'Cadereyta de Montes'),
	('Colón', 'Colón'),
	('Corregidora', 'Corregidora'),
	('Ezequiel Montes', 'Ezequiel Montes'),
	('Huimilpan', 'Huimilpan'),
	('Jalpan de Serra', 'Jalpan de Serra'),
	('Landa de Matamoros', 'Landa de Matamoros'),
	('El Marqués', 'El Marqués'),
	('Pedro Escobedo', 'Pedro Escobedo'),
	('Peñamiller', 'Peñamiller'),
	('Querétaro', 'Querétaro'),
	('San Joaquín', 'San Joaquín'),
	('San Juan del Río', 'San Juan del Río'),
	('Tequisquiapan', 'Tequisquiapan'),
	('Tolimán', 'Tolimán'),
	('Cozumel', 'Cozumel'),
	('Felipe Carrillo Puerto', 'Felipe Carrillo Puerto'),
	('Isla Mujeres', 'Isla Mujeres'),
	('Othón P. Blanco', 'Othón P. Blanco'),
	('Benito Juárez', 'Benito Juárez'),
	('José María Morelos', 'José María Morelos'),
	('Lázaro Cárdenas', 'Lázaro Cárdenas'),
	('Solidaridad', 'Solidaridad'),
	('Tulum', 'Tulum'),
	('Bacalar', 'Bacalar'),
	('Ahualulco', 'Ahualulco'),
	('Alaquines', 'Alaquines'),
	('Aquismón', 'Aquismón'),
	('Armadillo de los Infante', 'Armadillo de los Infante'),
	('Cárdenas', 'Cárdenas'),
	('Catorce', 'Catorce'),
	('Cedral', 'Cedral'),
	('Cerritos', 'Cerritos'),
	('Cerro de San Pedro', 'Cerro de San Pedro'),
	('Ciudad del Maíz', 'Ciudad del Maíz'),
	('Ciudad Fernández', 'Ciudad Fernández'),
	('Tancanhuitz', 'Tancanhuitz'),
	('Ciudad Valles', 'Ciudad Valles'),
	('Coxcatlán', 'Coxcatlán'),
	('Charcas', 'Charcas'),
	('Ebano', 'Ebano'),
	('Guadalcázar', 'Guadalcázar'),
	('Huehuetlán', 'Huehuetlán'),
	('Lagunillas', 'Lagunillas'),
	('Matehuala', 'Matehuala'),
	('Mexquitic de Carmona', 'Mexquitic de Carmona'),
	('Moctezuma', 'Moctezuma'),
	('Rayón', 'Rayón'),
	('Rioverde', 'Rioverde'),
	('Salinas', 'Salinas'),
	('San Antonio', 'San Antonio'),
	('San Ciro de Acosta', 'San Ciro de Acosta'),
	('San Luis Potosí', 'San Luis Potosí'),
	('San Martín Chalchicuautla', 'San Martín Chalchicuautla'),
	('San Nicolás Tolentino', 'San Nicolás Tolentino'),
	('Santa Catarina', 'Santa Catarina'),
	('Santa María del Río', 'Santa María del Río'),
	('Santo Domingo', 'Santo Domingo'),
	('San Vicente Tancuayalab', 'San Vicente Tancuayalab'),
	('Soledad de Graciano Sánchez', 'Soledad de Graciano Sánchez'),
	('Tamasopo', 'Tamasopo'),
	('Tamazunchale', 'Tamazunchale'),
	('Tampacán', 'Tampacán'),
	('Tampamolón Corona', 'Tampamolón Corona'),
	('Tamuín', 'Tamuín'),
	('Tanlajás', 'Tanlajás'),
	('Tanquián de Escobedo', 'Tanquián de Escobedo'),
	('Tierra Nueva', 'Tierra Nueva'),
	('Vanegas', 'Vanegas'),
	('Venado', 'Venado'),
	('Villa de Arriaga', 'Villa de Arriaga'),
	('Villa de Guadalupe', 'Villa de Guadalupe'),
	('Villa de la Paz', 'Villa de la Paz'),
	('Villa de Ramos', 'Villa de Ramos'),
	('Villa de Reyes', 'Villa de Reyes'),
	('Villa Hidalgo', 'Villa Hidalgo'),
	('Villa Juárez', 'Villa Juárez'),
	('Axtla de Terrazas', 'Axtla de Terrazas'),
	('Xilitla', 'Xilitla'),
	('Zaragoza', 'Zaragoza'),
	('Villa de Arista', 'Villa de Arista'),
	('Matlapa', 'Matlapa'),
	('El Naranjo', 'El Naranjo'),
	('Ahome', 'Ahome'),
	('Angostura', 'Angostura'),
	('Badiraguato', 'Badiraguato'),
	('Concordia', 'Concordia'),
	('Cosalá', 'Cosalá'),
	('Culiacán', 'Culiacán'),
	('Choix', 'Choix'),
	('Elota', 'Elota'),
	('Escuinapa', 'Escuinapa'),
	('El Fuerte', 'El Fuerte'),
	('Guasave', 'Guasave'),
	('Mazatlán', 'Mazatlán'),
	('Mocorito', 'Mocorito'),
	('Rosario', 'Rosario'),
	('Salvador Alvarado', 'Salvador Alvarado'),
	('San Ignacio', 'San Ignacio'),
	('Sinaloa', 'Sinaloa'),
	('Navolato', 'Navolato'),
	('Aconchi', 'Aconchi'),
	('Agua Prieta', 'Agua Prieta'),
	('Alamos', 'Alamos'),
	('Altar', 'Altar'),
	('Arivechi', 'Arivechi'),
	('Arizpe', 'Arizpe'),
	('Atil', 'Atil'),
	('Bacadéhuachi', 'Bacadéhuachi'),
	('Bacanora', 'Bacanora'),
	('Bacerac', 'Bacerac'),
	('Bacoachi', 'Bacoachi'),
	('Bácum', 'Bácum'),
	('Banámichi', 'Banámichi'),
	('Baviácora', 'Baviácora'),
	('Bavispe', 'Bavispe'),
	('Benjamín Hill', 'Benjamín Hill'),
	('Caborca', 'Caborca'),
	('Cajeme', 'Cajeme'),
	('Cananea', 'Cananea'),
	('Carbó', 'Carbó'),
	('La Colorada', 'La Colorada'),
	('Cucurpe', 'Cucurpe'),
	('Cumpas', 'Cumpas'),
	('Divisaderos', 'Divisaderos'),
	('Empalme', 'Empalme'),
	('Etchojoa', 'Etchojoa'),
	('Fronteras', 'Fronteras'),
	('Granados', 'Granados'),
	('Guaymas', 'Guaymas'),
	('Hermosillo', 'Hermosillo'),
	('Huachinera', 'Huachinera'),
	('Huásabas', 'Huásabas'),
	('Huatabampo', 'Huatabampo'),
	('Huépac', 'Huépac'),
	('Imuris', 'Imuris'),
	('Magdalena', 'Magdalena'),
	('Mazatán', 'Mazatán'),
	('Moctezuma', 'Moctezuma'),
	('Naco', 'Naco'),
	('Nácori Chico', 'Nácori Chico'),
	('Nacozari de García', 'Nacozari de García'),
	('Navojoa', 'Navojoa'),
	('Nogales', 'Nogales'),
	('Onavas', 'Onavas'),
	('Opodepe', 'Opodepe'),
	('Oquitoa', 'Oquitoa'),
	('Pitiquito', 'Pitiquito'),
	('Puerto Peñasco', 'Puerto Peñasco'),
	('Quiriego', 'Quiriego'),
	('Rayón', 'Rayón'),
	('Rosario', 'Rosario'),
	('Sahuaripa', 'Sahuaripa'),
	('San Felipe de Jesús', 'San Felipe de Jesús'),
	('San Javier', 'San Javier'),
	('San Luis Río Colorado', 'San Luis Río Colorado'),
	('San Miguel de Horcasitas', 'San Miguel de Horcasitas'),
	('San Pedro de la Cueva', 'San Pedro de la Cueva'),
	('Santa Ana', 'Santa Ana'),
	('Santa Cruz', 'Santa Cruz'),
	('Sáric', 'Sáric'),
	('Soyopa', 'Soyopa'),
	('Suaqui Grande', 'Suaqui Grande'),
	('Tepache', 'Tepache'),
	('Trincheras', 'Trincheras'),
	('Tubutama', 'Tubutama'),
	('Ures', 'Ures'),
	('Villa Hidalgo', 'Villa Hidalgo'),
	('Villa Pesqueira', 'Villa Pesqueira'),
	('Yécora', 'Yécora'),
	('General Plutarco Elías Calles', 'General Plutarco Elías Calles'),
	('Benito Juárez', 'Benito Juárez'),
	('San Ignacio Río Muerto', 'San Ignacio Río Muerto'),
	('Balancán', 'Balancán'),
	('Cárdenas', 'Cárdenas'),
	('Centla', 'Centla'),
	('Centro', 'Centro'),
	('Comalcalco', 'Comalcalco'),
	('Cunduacán', 'Cunduacán'),
	('Emiliano Zapata', 'Emiliano Zapata'),
	('Huimanguillo', 'Huimanguillo'),
	('Jalapa', 'Jalapa'),
	('Jalpa de Méndez', 'Jalpa de Méndez'),
	('Jonuta', 'Jonuta'),
	('Macuspana', 'Macuspana'),
	('Nacajuca', 'Nacajuca'),
	('Paraíso', 'Paraíso'),
	('Tacotalpa', 'Tacotalpa'),
	('Teapa', 'Teapa'),
	('Tenosique', 'Tenosique'),
	('Abasolo', 'Abasolo'),
	('Aldama', 'Aldama'),
	('Altamira', 'Altamira'),
	('Antiguo Morelos', 'Antiguo Morelos'),
	('Burgos', 'Burgos'),
	('Bustamante', 'Bustamante'),
	('Camargo', 'Camargo'),
	('Casas', 'Casas'),
	('Ciudad Madero', 'Ciudad Madero'),
	('Cruillas', 'Cruillas'),
	('Gómez Farías', 'Gómez Farías'),
	('González', 'González'),
	('Güémez', 'Güémez'),
	('Guerrero', 'Guerrero'),
	('Gustavo Díaz Ordaz', 'Gustavo Díaz Ordaz'),
	('Hidalgo', 'Hidalgo'),
	('Jaumave', 'Jaumave'),
	('Jiménez', 'Jiménez'),
	('Llera', 'Llera'),
	('Mainero', 'Mainero'),
	('El Mante', 'El Mante'),
	('Matamoros', 'Matamoros'),
	('Méndez', 'Méndez'),
	('Mier', 'Mier'),
	('Miguel Alemán', 'Miguel Alemán'),
	('Miquihuana', 'Miquihuana'),
	('Nuevo Laredo', 'Nuevo Laredo'),
	('Nuevo Morelos', 'Nuevo Morelos'),
	('Ocampo', 'Ocampo'),
	('Padilla', 'Padilla'),
	('Palmillas', 'Palmillas'),
	('Reynosa', 'Reynosa'),
	('Río Bravo', 'Río Bravo'),
	('San Carlos', 'San Carlos'),
	('San Fernando', 'San Fernando'),
	('San Nicolás', 'San Nicolás'),
	('Soto la Marina', 'Soto la Marina'),
	('Tampico', 'Tampico'),
	('Tula', 'Tula'),
	('Valle Hermoso', 'Valle Hermoso'),
	('Victoria', 'Victoria'),
	('Villagrán', 'Villagrán'),
	('Xicoténcatl', 'Xicoténcatl'),
	('Amaxac de Guerrero', 'Amaxac de Guerrero'),
	('Apetatitlán de Antonio Carvajal', 'Apetatitlán de Antonio Carvajal'),
	('Atlangatepec', 'Atlangatepec'),
	('Altzayanca', 'Altzayanca'),
	('Apizaco', 'Apizaco'),
	('Calpulalpan', 'Calpulalpan'),
	('El Carmen Tequexquitla', 'El Carmen Tequexquitla'),
	('Cuapiaxtla', 'Cuapiaxtla'),
	('Cuaxomulco', 'Cuaxomulco'),
	('Chiautempan', 'Chiautempan'),
	('Muñoz de Domingo Arenas', 'Muñoz de Domingo Arenas'),
	('Españita', 'Españita'),
	('Huamantla', 'Huamantla'),
	('Hueyotlipan', 'Hueyotlipan'),
	('Ixtacuixtla de Mariano Matamoros', 'Ixtacuixtla de Mariano Matamoros'),
	('Ixtenco', 'Ixtenco'),
	('Mazatecochco de José María Morelos', 'Mazatecochco de José María Morelos'),
	('Contla de Juan Cuamatzi', 'Contla de Juan Cuamatzi'),
	('Tepetitla de Lardizábal', 'Tepetitla de Lardizábal'),
	('Sanctórum de Lázaro Cárdenas', 'Sanctórum de Lázaro Cárdenas'),
	('Nanacamilpa de Mariano Arista', 'Nanacamilpa de Mariano Arista'),
	('Acuamanala de Miguel Hidalgo', 'Acuamanala de Miguel Hidalgo'),
	('Natívitas', 'Natívitas'),
	('Panotla', 'Panotla'),
	('San Pablo del Monte', 'San Pablo del Monte'),
	('Santa Cruz Tlaxcala', 'Santa Cruz Tlaxcala'),
	('Tenancingo', 'Tenancingo'),
	('Teolocholco', 'Teolocholco'),
	('Tepeyanco', 'Tepeyanco'),
	('Terrenate', 'Terrenate'),
	('Tetla de la Solidaridad', 'Tetla de la Solidaridad'),
	('Tetlatlahuca', 'Tetlatlahuca'),
	('Tlaxcala', 'Tlaxcala'),
	('Tlaxco', 'Tlaxco'),
	('Tocatlán', 'Tocatlán'),
	('Totolac', 'Totolac'),
	('Ziltlaltépec de Trinidad Sánchez Santos', 'Ziltlaltépec de Trinidad Sánchez Santos'),
	('Tzompantepec', 'Tzompantepec'),
	('Xaloztoc', 'Xaloztoc'),
	('Xaltocan', 'Xaltocan'),
	('Papalotla de Xicohténcatl', 'Papalotla de Xicohténcatl'),
	('Xicohtzinco', 'Xicohtzinco'),
	('Yauhquemehcan', 'Yauhquemehcan'),
	('Zacatelco', 'Zacatelco'),
	('Benito Juárez', 'Benito Juárez'),
	('Emiliano Zapata', 'Emiliano Zapata'),
	('Lázaro Cárdenas', 'Lázaro Cárdenas'),
	('La Magdalena Tlaltelulco', 'La Magdalena Tlaltelulco'),
	('San Damián Texóloc', 'San Damián Texóloc'),
	('San Francisco Tetlanohcan', 'San Francisco Tetlanohcan'),
	('San Jerónimo Zacualpan', 'San Jerónimo Zacualpan'),
	('San José Teacalco', 'San José Teacalco'),
	('San Juan Huactzinco', 'San Juan Huactzinco'),
	('San Lorenzo Axocomanitla', 'San Lorenzo Axocomanitla'),
	('San Lucas Tecopilco', 'San Lucas Tecopilco'),
	('Santa Ana Nopalucan', 'Santa Ana Nopalucan'),
	('Santa Apolonia Teacalco', 'Santa Apolonia Teacalco'),
	('Santa Catarina Ayometla', 'Santa Catarina Ayometla'),
	('Santa Cruz Quilehtla', 'Santa Cruz Quilehtla'),
	('Santa Isabel Xiloxoxtla', 'Santa Isabel Xiloxoxtla'),
	('Acajete', 'Acajete'),
	('Acatlán', 'Acatlán'),
	('Acayucan', 'Acayucan'),
	('Actopan', 'Actopan'),
	('Acula', 'Acula'),
	('Acultzingo', 'Acultzingo'),
	('Camarón de Tejeda', 'Camarón de Tejeda'),
	('Alpatláhuac', 'Alpatláhuac'),
	('Alto Lucero de Gutiérrez Barrios', 'Alto Lucero de Gutiérrez Barrios'),
	('Altotonga', 'Altotonga'),
	('Alvarado', 'Alvarado'),
	('Amatitlán', 'Amatitlán'),
	('Naranjos Amatlán', 'Naranjos Amatlán'),
	('Amatlán de los Reyes', 'Amatlán de los Reyes'),
	('Angel R. Cabada', 'Angel R. Cabada'),
	('La Antigua', 'La Antigua'),
	('Apazapan', 'Apazapan'),
	('Aquila', 'Aquila'),
	('Astacinga', 'Astacinga'),
	('Atlahuilco', 'Atlahuilco'),
	('Atoyac', 'Atoyac'),
	('Atzacan', 'Atzacan'),
	('Atzalan', 'Atzalan'),
	('Tlaltetela', 'Tlaltetela'),
	('Ayahualulco', 'Ayahualulco'),
	('Banderilla', 'Banderilla'),
	('Benito Juárez', 'Benito Juárez'),
	('Boca del Río', 'Boca del Río'),
	('Calcahualco', 'Calcahualco'),
	('Camerino Z. Mendoza', 'Camerino Z. Mendoza'),
	('Carrillo Puerto', 'Carrillo Puerto'),
	('Catemaco', 'Catemaco'),
	('Cazones de Herrera', 'Cazones de Herrera'),
	('Cerro Azul', 'Cerro Azul'),
	('Citlaltépetl', 'Citlaltépetl'),
	('Coacoatzintla', 'Coacoatzintla'),
	('Coahuitlán', 'Coahuitlán'),
	('Coatepec', 'Coatepec'),
	('Coatzacoalcos', 'Coatzacoalcos'),
	('Coatzintla', 'Coatzintla'),
	('Coetzala', 'Coetzala'),
	('Colipa', 'Colipa'),
	('Comapa', 'Comapa'),
	('Córdoba', 'Córdoba'),
	('Cosamaloapan de Carpio', 'Cosamaloapan de Carpio'),
	('Cosautlán de Carvajal', 'Cosautlán de Carvajal'),
	('Coscomatepec', 'Coscomatepec'),
	('Cosoleacaque', 'Cosoleacaque'),
	('Cotaxtla', 'Cotaxtla'),
	('Coxquihui', 'Coxquihui'),
	('Coyutla', 'Coyutla'),
	('Cuichapa', 'Cuichapa'),
	('Cuitláhuac', 'Cuitláhuac'),
	('Chacaltianguis', 'Chacaltianguis'),
	('Chalma', 'Chalma'),
	('Chiconamel', 'Chiconamel'),
	('Chiconquiaco', 'Chiconquiaco'),
	('Chicontepec', 'Chicontepec'),
	('Chinameca', 'Chinameca'),
	('Chinampa de Gorostiza', 'Chinampa de Gorostiza'),
	('Las Choapas', 'Las Choapas'),
	('Chocamán', 'Chocamán'),
	('Chontla', 'Chontla'),
	('Chumatlán', 'Chumatlán'),
	('Emiliano Zapata', 'Emiliano Zapata'),
	('Espinal', 'Espinal'),
	('Filomeno Mata', 'Filomeno Mata'),
	('Fortín', 'Fortín'),
	('Gutiérrez Zamora', 'Gutiérrez Zamora'),
	('Hidalgotitlán', 'Hidalgotitlán'),
	('Huatusco', 'Huatusco'),
	('Huayacocotla', 'Huayacocotla'),
	('Hueyapan de Ocampo', 'Hueyapan de Ocampo'),
	('Huiloapan de Cuauhtémoc', 'Huiloapan de Cuauhtémoc'),
	('Ignacio de la Llave', 'Ignacio de la Llave'),
	('Ilamatlán', 'Ilamatlán'),
	('Isla', 'Isla'),
	('Ixcatepec', 'Ixcatepec'),
	('Ixhuacán de los Reyes', 'Ixhuacán de los Reyes'),
	('Ixhuatlán del Café', 'Ixhuatlán del Café'),
	('Ixhuatlancillo', 'Ixhuatlancillo'),
	('Ixhuatlán del Sureste', 'Ixhuatlán del Sureste'),
	('Ixhuatlán de Madero', 'Ixhuatlán de Madero'),
	('Ixmatlahuacan', 'Ixmatlahuacan'),
	('Ixtaczoquitlán', 'Ixtaczoquitlán'),
	('Jalacingo', 'Jalacingo'),
	('Xalapa', 'Xalapa'),
	('Jalcomulco', 'Jalcomulco'),
	('Jáltipan', 'Jáltipan'),
	('Jamapa', 'Jamapa'),
	('Jesús Carranza', 'Jesús Carranza'),
	('Xico', 'Xico'),
	('Jilotepec', 'Jilotepec'),
	('Juan Rodríguez Clara', 'Juan Rodríguez Clara'),
	('Juchique de Ferrer', 'Juchique de Ferrer'),
	('Landero y Coss', 'Landero y Coss'),
	('Lerdo de Tejada', 'Lerdo de Tejada'),
	('Magdalena', 'Magdalena'),
	('Maltrata', 'Maltrata'),
	('Manlio Fabio Altamirano', 'Manlio Fabio Altamirano'),
	('Mariano Escobedo', 'Mariano Escobedo'),
	('Martínez de la Torre', 'Martínez de la Torre'),
	('Mecatlán', 'Mecatlán'),
	('Mecayapan', 'Mecayapan'),
	('Medellín', 'Medellín'),
	('Miahuatlán', 'Miahuatlán'),
	('Las Minas', 'Las Minas'),
	('Minatitlán', 'Minatitlán'),
	('Misantla', 'Misantla'),
	('Mixtla de Altamirano', 'Mixtla de Altamirano'),
	('Moloacán', 'Moloacán'),
	('Naolinco', 'Naolinco'),
	('Naranjal', 'Naranjal'),
	('Nautla', 'Nautla'),
	('Nogales', 'Nogales'),
	('Oluta', 'Oluta'),
	('Omealca', 'Omealca'),
	('Orizaba', 'Orizaba'),
	('Otatitlán', 'Otatitlán'),
	('Oteapan', 'Oteapan'),
	('Ozuluama de Mascareñas', 'Ozuluama de Mascareñas'),
	('Pajapan', 'Pajapan'),
	('Pánuco', 'Pánuco'),
	('Papantla', 'Papantla'),
	('Paso del Macho', 'Paso del Macho'),
	('Paso de Ovejas', 'Paso de Ovejas'),
	('La Perla', 'La Perla'),
	('Perote', 'Perote'),
	('Platón Sánchez', 'Platón Sánchez'),
	('Playa Vicente', 'Playa Vicente'),
	('Poza Rica de Hidalgo', 'Poza Rica de Hidalgo'),
	('Las Vigas de Ramírez', 'Las Vigas de Ramírez'),
	('Pueblo Viejo', 'Pueblo Viejo'),
	('Puente Nacional', 'Puente Nacional'),
	('Rafael Delgado', 'Rafael Delgado'),
	('Rafael Lucio', 'Rafael Lucio'),
	('Los Reyes', 'Los Reyes'),
	('Río Blanco', 'Río Blanco'),
	('Saltabarranca', 'Saltabarranca'),
	('San Andrés Tenejapan', 'San Andrés Tenejapan'),
	('San Andrés Tuxtla', 'San Andrés Tuxtla'),
	('San Juan Evangelista', 'San Juan Evangelista'),
	('Santiago Tuxtla', 'Santiago Tuxtla'),
	('Sayula de Alemán', 'Sayula de Alemán'),
	('Soconusco', 'Soconusco'),
	('Sochiapa', 'Sochiapa'),
	('Soledad Atzompa', 'Soledad Atzompa'),
	('Soledad de Doblado', 'Soledad de Doblado'),
	('Soteapan', 'Soteapan'),
	('Tamalín', 'Tamalín'),
	('Tamiahua', 'Tamiahua'),
	('Tampico Alto', 'Tampico Alto'),
	('Tancoco', 'Tancoco'),
	('Tantima', 'Tantima'),
	('Tantoyuca', 'Tantoyuca'),
	('Tatatila', 'Tatatila'),
	('Castillo de Teayo', 'Castillo de Teayo'),
	('Tecolutla', 'Tecolutla'),
	('Tehuipango', 'Tehuipango'),
	('Álamo Temapache', 'Álamo Temapache'),
	('Tempoal', 'Tempoal'),
	('Tenampa', 'Tenampa'),
	('Tenochtitlán', 'Tenochtitlán'),
	('Teocelo', 'Teocelo'),
	('Tepatlaxco', 'Tepatlaxco'),
	('Tepetlán', 'Tepetlán'),
	('Tepetzintla', 'Tepetzintla'),
	('Tequila', 'Tequila'),
	('José Azueta', 'José Azueta'),
	('Texcatepec', 'Texcatepec'),
	('Texhuacán', 'Texhuacán'),
	('Texistepec', 'Texistepec'),
	('Tezonapa', 'Tezonapa'),
	('Tierra Blanca', 'Tierra Blanca'),
	('Tihuatlán', 'Tihuatlán'),
	('Tlacojalpan', 'Tlacojalpan'),
	('Tlacolulan', 'Tlacolulan'),
	('Tlacotalpan', 'Tlacotalpan'),
	('Tlacotepec de Mejía', 'Tlacotepec de Mejía'),
	('Tlachichilco', 'Tlachichilco'),
	('Tlalixcoyan', 'Tlalixcoyan'),
	('Tlalnelhuayocan', 'Tlalnelhuayocan'),
	('Tlapacoyan', 'Tlapacoyan'),
	('Tlaquilpa', 'Tlaquilpa'),
	('Tlilapan', 'Tlilapan'),
	('Tomatlán', 'Tomatlán'),
	('Tonayán', 'Tonayán'),
	('Totutla', 'Totutla'),
	('Tuxpan', 'Tuxpan'),
	('Tuxtilla', 'Tuxtilla'),
	('Ursulo Galván', 'Ursulo Galván'),
	('Vega de Alatorre', 'Vega de Alatorre'),
	('Veracruz', 'Veracruz'),
	('Villa Aldama', 'Villa Aldama'),
	('Xoxocotla', 'Xoxocotla'),
	('Yanga', 'Yanga'),
	('Yecuatla', 'Yecuatla'),
	('Zacualpan', 'Zacualpan'),
	('Zaragoza', 'Zaragoza'),
	('Zentla', 'Zentla'),
	('Zongolica', 'Zongolica'),
	('Zontecomatlán de López y Fuentes', 'Zontecomatlán de López y Fuentes'),
	('Zozocolco de Hidalgo', 'Zozocolco de Hidalgo'),
	('Agua Dulce', 'Agua Dulce'),
	('El Higo', 'El Higo'),
	('Nanchital de Lázaro Cárdenas del Río', 'Nanchital de Lázaro Cárdenas del Río'),
	('Tres Valles', 'Tres Valles'),
	('Carlos A. Carrillo', 'Carlos A. Carrillo'),
	('Tatahuicapan de Juárez', 'Tatahuicapan de Juárez'),
	('Uxpanapa', 'Uxpanapa'),
	('San Rafael', 'San Rafael'),
	('Santiago Sochiapan', 'Santiago Sochiapan'),
	('Abalá', 'Abalá'),
	('Acanceh', 'Acanceh'),
	('Akil', 'Akil'),
	('Baca', 'Baca'),
	('Bokobá', 'Bokobá'),
	('Buctzotz', 'Buctzotz'),
	('Cacalchén', 'Cacalchén'),
	('Calotmul', 'Calotmul'),
	('Cansahcab', 'Cansahcab'),
	('Cantamayec', 'Cantamayec'),
	('Celestún', 'Celestún'),
	('Cenotillo', 'Cenotillo'),
	('Conkal', 'Conkal'),
	('Cuncunul', 'Cuncunul'),
	('Cuzamá', 'Cuzamá'),
	('Chacsinkín', 'Chacsinkín'),
	('Chankom', 'Chankom'),
	('Chapab', 'Chapab'),
	('Chemax', 'Chemax'),
	('Chicxulub Pueblo', 'Chicxulub Pueblo'),
	('Chichimilá', 'Chichimilá'),
	('Chikindzonot', 'Chikindzonot'),
	('Chocholá', 'Chocholá'),
	('Chumayel', 'Chumayel'),
	('Dzán', 'Dzán'),
	('Dzemul', 'Dzemul'),
	('Dzidzantún', 'Dzidzantún'),
	('Dzilam de Bravo', 'Dzilam de Bravo'),
	('Dzilam González', 'Dzilam González'),
	('Dzitás', 'Dzitás'),
	('Dzoncauich', 'Dzoncauich'),
	('Espita', 'Espita'),
	('Halachó', 'Halachó'),
	('Hocabá', 'Hocabá'),
	('Hoctún', 'Hoctún'),
	('Homún', 'Homún'),
	('Huhí', 'Huhí'),
	('Hunucmá', 'Hunucmá'),
	('Ixil', 'Ixil'),
	('Izamal', 'Izamal'),
	('Kanasín', 'Kanasín'),
	('Kantunil', 'Kantunil'),
	('Kaua', 'Kaua'),
	('Kinchil', 'Kinchil'),
	('Kopomá', 'Kopomá'),
	('Mama', 'Mama'),
	('Maní', 'Maní'),
	('Maxcanú', 'Maxcanú'),
	('Mayapán', 'Mayapán'),
	('Mérida', 'Mérida'),
	('Mocochá', 'Mocochá'),
	('Motul', 'Motul'),
	('Muna', 'Muna'),
	('Muxupip', 'Muxupip'),
	('Opichén', 'Opichén'),
	('Oxkutzcab', 'Oxkutzcab'),
	('Panabá', 'Panabá'),
	('Peto', 'Peto'),
	('Progreso', 'Progreso'),
	('Quintana Roo', 'Quintana Roo'),
	('Río Lagartos', 'Río Lagartos'),
	('Sacalum', 'Sacalum'),
	('Samahil', 'Samahil'),
	('Sanahcat', 'Sanahcat'),
	('San Felipe', 'San Felipe'),
	('Santa Elena', 'Santa Elena'),
	('Seyé', 'Seyé'),
	('Sinanché', 'Sinanché'),
	('Sotuta', 'Sotuta'),
	('Sucilá', 'Sucilá'),
	('Sudzal', 'Sudzal'),
	('Suma', 'Suma'),
	('Tahdziú', 'Tahdziú'),
	('Tahmek', 'Tahmek'),
	('Teabo', 'Teabo'),
	('Tecoh', 'Tecoh'),
	('Tekal de Venegas', 'Tekal de Venegas'),
	('Tekantó', 'Tekantó'),
	('Tekax', 'Tekax'),
	('Tekit', 'Tekit'),
	('Tekom', 'Tekom'),
	('Telchac Pueblo', 'Telchac Pueblo'),
	('Telchac Puerto', 'Telchac Puerto'),
	('Temax', 'Temax'),
	('Temozón', 'Temozón'),
	('Tepakán', 'Tepakán'),
	('Tetiz', 'Tetiz'),
	('Teya', 'Teya'),
	('Ticul', 'Ticul'),
	('Timucuy', 'Timucuy'),
	('Tinum', 'Tinum'),
	('Tixcacalcupul', 'Tixcacalcupul'),
	('Tixkokob', 'Tixkokob'),
	('Tixmehuac', 'Tixmehuac'),
	('Tixpéhual', 'Tixpéhual'),
	('Tizimín', 'Tizimín'),
	('Tunkás', 'Tunkás'),
	('Tzucacab', 'Tzucacab'),
	('Uayma', 'Uayma'),
	('Ucú', 'Ucú'),
	('Umán', 'Umán'),
	('Valladolid', 'Valladolid'),
	('Xocchel', 'Xocchel'),
	('Yaxcabá', 'Yaxcabá'),
	('Yaxkukul', 'Yaxkukul'),
	('Yobaín', 'Yobaín'),
	('Apozol', 'Apozol'),
	('Apulco', 'Apulco'),
	('Atolinga', 'Atolinga'),
	('Benito Juárez', 'Benito Juárez'),
	('Calera', 'Calera'),
	('Cañitas de Felipe Pescador', 'Cañitas de Felipe Pescador'),
	('Concepción del Oro', 'Concepción del Oro'),
	('Cuauhtémoc', 'Cuauhtémoc'),
	('Chalchihuites', 'Chalchihuites'),
	('Fresnillo', 'Fresnillo'),
	('Trinidad García de la Cadena', 'Trinidad García de la Cadena'),
	('Genaro Codina', 'Genaro Codina'),
	('General Enrique Estrada', 'General Enrique Estrada'),
	('General Francisco R. Murguía', 'General Francisco R. Murguía'),
	('El Plateado de Joaquín Amaro', 'El Plateado de Joaquín Amaro'),
	('General Pánfilo Natera', 'General Pánfilo Natera'),
	('Guadalupe', 'Guadalupe'),
	('Huanusco', 'Huanusco'),
	('Jalpa', 'Jalpa'),
	('Jerez', 'Jerez'),
	('Jiménez del Teul', 'Jiménez del Teul'),
	('Juan Aldama', 'Juan Aldama'),
	('Juchipila', 'Juchipila'),
	('Loreto', 'Loreto'),
	('Luis Moya', 'Luis Moya'),
	('Mazapil', 'Mazapil'),
	('Melchor Ocampo', 'Melchor Ocampo'),
	('Mezquital del Oro', 'Mezquital del Oro'),
	('Miguel Auza', 'Miguel Auza'),
	('Momax', 'Momax'),
	('Monte Escobedo', 'Monte Escobedo'),
	('Morelos', 'Morelos'),
	('Moyahua de Estrada', 'Moyahua de Estrada'),
	('Nochistlán de Mejía', 'Nochistlán de Mejía'),
	('Noria de Ángeles', 'Noria de Ángeles'),
	('Ojocaliente', 'Ojocaliente'),
	('Pánuco', 'Pánuco'),
	('Pinos', 'Pinos'),
	('Río Grande', 'Río Grande'),
	('Sain Alto', 'Sain Alto'),
	('El Salvador', 'El Salvador'),
	('Sombrerete', 'Sombrerete'),
	('Susticacán', 'Susticacán'),
	('Tabasco', 'Tabasco'),
	('Tepechitlán', 'Tepechitlán'),
	('Tepetongo', 'Tepetongo'),
	('Teúl de González Ortega', 'Teúl de González Ortega'),
	('Tlaltenango de Sánchez Román', 'Tlaltenango de Sánchez Román'),
	('Valparaíso', 'Valparaíso'),
	('Vetagrande', 'Vetagrande'),
	('Villa de Cos', 'Villa de Cos'),
	('Villa García', 'Villa García'),
	('Villa González Ortega', 'Villa González Ortega'),
	('Villa Hidalgo', 'Villa Hidalgo'),
	('Villanueva', 'Villanueva'),
	('Zacatecas', 'Zacatecas'),
	('Trancoso', 'Trancoso'),
	('Santa María de la Paz', 'Santa María de la Paz'),
	)