# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 00:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CID', models.CharField(max_length=10, unique=True, verbose_name='ID')),
                ('NAME', models.CharField(blank=True, max_length=150)),
                ('COMPANY', models.CharField(blank=True, max_length=150)),
                ('RFC', models.CharField(blank=True, max_length=50, unique=True)),
                ('DATE_1', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('NAME',),
                'default_permissions': ('add', 'change', 'delete', 'view'),
                'verbose_name': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='Contacts_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('POSITION', models.CharField(blank=True, max_length=50)),
                ('CONTACT_NAME_1', models.CharField(max_length=50)),
                ('PHONE_1', models.CharField(max_length=10)),
                ('EXT_1', models.CharField(max_length=5)),
                ('MAIL_1', models.EmailField(blank=True, max_length=50)),
                ('PHONE_2', models.CharField(blank=True, max_length=10)),
                ('EXT_2', models.CharField(blank=True, max_length=5)),
                ('MAIL_2', models.EmailField(blank=True, max_length=50)),
                ('COMPANY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Clients')),
            ],
        ),
    ]
