# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='CID',
            field=models.CharField(max_length=6, unique=True, verbose_name='ID'),
        ),
    ]
