# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 22:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de Registro')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualizaci\xf3n')),
                ('order', models.CharField(max_length=100, verbose_name='OC')),
                ('bpid', models.CharField(max_length=100, verbose_name='ID de Orden')),
                ('lq', models.CharField(max_length=100, verbose_name='LEQ')),
                ('flag', models.CharField(blank=True, max_length=1)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Clients', verbose_name='Escoge a un cliente')),
                ('packer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Escoge un empacador')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='Escoge un producto')),
            ],
            options={
                'ordering': ('-id',),
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
    ]
