# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 23:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='client_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Nombre de cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='packer_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Nombre de empacador'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='flag',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
