# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 02:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20171109_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='product_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Nombre de producto'),
            preserve_default=False,
        ),
    ]
