# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orders_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='bpid',
            field=models.CharField(max_length=100, unique=True, verbose_name='ID de Orden'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='lq',
            field=models.CharField(max_length=100, unique=True, verbose_name='LEQ'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order',
            field=models.CharField(max_length=100, unique=True, verbose_name='OC'),
        ),
    ]
