# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-18 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20171115_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pallets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=35, verbose_name='Tarima')),
            ],
            options={
                'ordering': ('-id',),
                'default_permissions': ('add', 'change', 'delete', 'view'),
                'verbose_name': 'Tarima',
                'verbose_name_plural': 'Tarimas',
            },
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ('-id',), 'verbose_name': 'Orden', 'verbose_name_plural': 'Ordenes'},
        ),
        migrations.AddField(
            model_name='pallets',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Orders', verbose_name='Orden de Compra'),
        ),
    ]
