# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orders_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='expiration',
            field=models.DateField(blank=True, null=True, verbose_name='Caducidad'),
        ),
    ]
