# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20171204_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0, verbose_name='Peso de la Bajada')),
                ('pallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Pallets', verbose_name='Lista Asociada')),
            ],
        ),
        migrations.CreateModel(
            name='Rolls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.PositiveIntegerField()),
                ('weight', models.FloatField(default=0, verbose_name='Peso del Rollo')),
                ('delta_weight', models.FloatField(default=0, verbose_name='Diferencia de Peso')),
                ('sigma_weight', models.FloatField(default=0, verbose_name='Sumatoria de Peso')),
                ('serie', models.CharField(max_length=1, verbose_name='Serie')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Orders', verbose_name='Orden de Compra')),
            ],
        ),
        migrations.AddField(
            model_name='drops',
            name='roll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Rolls', verbose_name='Rollo'),
        ),
    ]
