# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-06 06:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20171206_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Clients', verbose_name='Escoge a un cliente'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='packer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Escoge un empacador'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='Escoge un producto'),
        ),
    ]
