# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-06 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20171206_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='pallets',
            name='pallet_weight',
            field=models.FloatField(default=0, verbose_name='Peso de Tarima'),
        ),
        migrations.AddField(
            model_name='pallets',
            name='weight',
            field=models.FloatField(default=0, verbose_name='Peso de Rollos'),
        ),
    ]
