# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 00:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20171206_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drop_Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0, verbose_name='Peso de la Bajada')),
            ],
        ),
        migrations.RemoveField(
            model_name='drops',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='rolls',
            name='delta_weight',
        ),
        migrations.RemoveField(
            model_name='rolls',
            name='rid',
        ),
        migrations.RemoveField(
            model_name='rolls',
            name='serie',
        ),
        migrations.RemoveField(
            model_name='rolls',
            name='sigma_weight',
        ),
        migrations.RemoveField(
            model_name='rolls',
            name='weight',
        ),
        migrations.AddField(
            model_name='drops',
            name='serie',
            field=models.CharField(default=0, max_length=1, verbose_name='Serie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drops',
            name='total_weight',
            field=models.FloatField(default=0, verbose_name='Peso de la Serie'),
        ),
        migrations.AddField(
            model_name='rolls',
            name='roll_name',
            field=models.CharField(default=1, max_length=2, verbose_name='N\xfamero de Rollo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rolls',
            name='total_weight',
            field=models.FloatField(default=0, verbose_name='Sumatoria de Peso'),
        ),
        migrations.AddField(
            model_name='drop_number',
            name='drop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Drops', verbose_name='Serie de Bajada'),
        ),
        migrations.AddField(
            model_name='drop_number',
            name='pallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Pallets', verbose_name='Tarima Asignada'),
        ),
    ]
