# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20171206_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolls',
            name='roll_name',
            field=models.CharField(max_length=3, verbose_name='N\xfamero de Rollo'),
        ),
    ]
