# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 23:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20171207_0338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drop_number',
            options={'ordering': ('drop__roll__roll_name', 'drop_name')},
        ),
    ]
