# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-09 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20171207_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='delta_weight',
            field=models.FloatField(default=0, verbose_name='Diferencia de Peso'),
        ),
        migrations.AddField(
            model_name='orders',
            name='qty',
            field=models.FloatField(default=0, verbose_name='Cantidad'),
        ),
        migrations.AddField(
            model_name='orders',
            name='weight',
            field=models.FloatField(default=0, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='pallets',
            name='pallet_weight',
            field=models.FloatField(default=14.5, verbose_name='Peso de Tarima'),
        ),
    ]
