# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-09 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20171209_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Registro'),
        ),
    ]
