# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de Registro')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualizaci\xf3n')),
                ('pid', models.CharField(blank=True, max_length=100, verbose_name='ID de Producto')),
                ('product', models.CharField(max_length=30, unique=True, verbose_name='Descripci\xf3n del Producto')),
                ('qty', models.FloatField(verbose_name='Cantidad')),
                ('unity', models.CharField(choices=[('kgs', 'Kilogramos'), ('millar', 'Millar')], default='kgs', max_length=10, verbose_name='Unidad')),
                ('Clientes', models.ManyToManyField(to='clients.Clients', verbose_name='Clientes asociados a Producto')),
            ],
            options={
                'ordering': ('-id',),
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
    ]
