# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product',
            field=models.CharField(max_length=200, unique=True, verbose_name='Descripci\xf3n del Producto'),
        ),
    ]
