# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-27 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hidden',
            field=models.CharField(default=None, max_length=200, null=True, verbose_name='Descripci\xf3n del Producto'),
            preserve_default=False,
        ),
    ]
