# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-27 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID de Producto'),
        ),
    ]
