# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-27 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_product_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hidden',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, null=True, verbose_name='Descripci\xf3n del Producto'),
            preserve_default=False,
        ),
    ]
