# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-27 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='hidden',
            field=models.CharField(max_length=200, null=True, verbose_name='Descripci\xf3n del Producto'),
        ),
    ]
