# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-27 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20171127_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='hidden',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
