# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20171127_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unity',
            field=models.CharField(choices=[('kgs', 'kgs.'), ('millar', 'M.')], default='kgs', max_length=10, verbose_name='Unidad'),
        ),
    ]
